if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([200000, 0, 'Personality test'
    , 'The Big Five Personality Test (mini)<br><br>'
            + '<a href="?test=2100000"><b>Norsk</b><br>Ogs&aring; kjent som Femfaktormodellen (FFM)</a><br><br>'
            + '<a href="?test=2800000"><b>Biases</b><br>to be extra aware of based upon your views</a><br><br>'
        +'also known as the Five - Factor Model(FFM), is a widely used framework in psychology to measure and describe personality traits.The traits are considered to represent broad dimensions of personality and are used to describe and understand individual differences in personality characteristics.It\'s important to note that individuals can possess a combination of high and low scores on each trait, resulting in unique personality profiles.'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for milj&oslash;, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:']);

big6.push([210000, 200000, 'Open&shy;ness','Open&shy;ness to Experi&shy;ence reflects a person\'s inclination towards novelty, imagination, creativity, and intellectual curiosity. Individuals high in openness tend to be imaginative, open-minded, adventurous, and appreciate art and beauty. Those low in openness are more conventional, practical, and prefer routine and familiarity.','','','','']);
big6.push([211000, 210000,'','','Endless possibilities inspire me to explore new ideas and push the boundaries of what is known','I prefer sticking to what I know and feel comfortable with, as it provides a sense of security and predictability','The desire to embrace life\'s possibilities drives me to constantly seek new experiences and adventures, ensuring I have no regrets','The uncertainty surrounding the unknown inhibits me from venturing outside of my comfort zone and exploring new things']);
big6.push([212000, 210000,'','','Embracing novel ideas and unconventional thinking expands my perspective and fosters personal growth','I find comfort in sticking to familiar routines and established methods, as they provide a sense of stability and security','Venturing into unexplored territories fuels my desire for constant self-improvement and discovery','The fear of the unknown prevents me from stepping outside of my comfort zone and trying new things']);
big6.push([220000, 200000,'Dil&shy;i&shy;gence','Conscientiousness refers to the degree of organization, responsibility, dependability, and self-discipline in an individual. Highly conscientious individuals are diligent, reliable, organized, and self-motivated, while those low in conscientiousness may be more spontaneous, laid-back, and less focused on details.','','','','']);
big6.push([221000, 220000,'','','Setting high standards and striving for excellence allows me to achieve remarkable results and reach my full potential','Being less focused on details and rules allows me the freedom to explore different approaches and embrace spontaneity','The drive to excel and meet others\' expectations fuels my determination to meticulously plan and execute tasks flawlessly','The aversion to constraints and inflexible systems makes me reluctant to adhere to rules and rigid schedules']);
big6.push([222000, 220000,'','','Being organized and detail-oriented allows me to stay on top of my responsibilities and achieve desired outcomes','I value flexibility and spontaneity, as they allow me to adapt and respond effectively to changing circumstances','Striving for perfection and meeting high standards propels me to excel in various aspects of life','The fear of restrictions and rigid structures makes me resist following rules and adhering to strict schedules']);
big6.push([230000, 200000,'Extra&shy;version','This trait captures a person\'s sociability, assertiveness, talkativeness, and level of outgoingness. Extroverted individuals tend to be energetic, enthusiastic, and seek social interactions. They are often described as outgoing and gain energy from being around others. Introverted individuals, on the other hand, prefer solitude, tend to be more reserved, and may feel drained by extensive social interactions.','','','','']);
big6.push([231000, 230000,'','','The excitement of social interactions and the potential for new connections energize and inspire me to constantly seek out others','Solitude and introspection provide the necessary space to unleash my creativity and delve deeper into my thoughts and ideas','The preference to avoid feelings of loneliness and the fear of missing out on social opportunities motivate me to constantly seek the company of others','The discomfort associated with social interactions and overwhelming stimuli causes me to withdraw and steer clear of situations that may lead to unease']);
big6.push([232000, 230000,'','','Engaging in social activities energizes me and helps me thrive in dynamic and collaborative environments','I find solace in solitude and introspection, which provide the space for self-reflection and recharge','The fear of missing out on social opportunities drives me to seek the company of others and engage in social interactions','The fear of overwhelming social interactions and stimuli leads me to withdraw and avoid situations that may cause discomfort']);
big6.push([240000, 200000,'Ami&shy;abil&shy;ity','Agreeableness reflects a person\'s tendency to be compassionate, cooperative, empathetic, and considerate of others. Those high in agreeableness are typically friendly, helpful, trusting, and prioritize harmonious relationships. Individuals low in agreeableness may be more skeptical, competitive, and assertive.','','','','']);
big6.push([241000, 240000,'','','The belief in the power of cooperation and compassion motivates me to create harmony and make a positive impact on others','Asserting my own needs and boundaries allows me the freedom to pursue my goals and desires without feeling restricted','The preference to maintain harmony and avoid conflict and disapproval drives me to prioritize peaceful interactions and steer clear of confrontations','The inclination to protect myself from vulnerability and dependency results in guardedness and prioritizing self-preservation over forming close relationships']);
big6.push([242000, 240000,'','','Valuing harmony and empathy allows me to build strong and meaningful connections with others','Asserting my opinions and boundaries enables me to maintain my individuality and personal growth','The fear of conflict and disapproval drives me to prioritize maintaining peace and avoiding any confrontations','The fear of vulnerability and dependence leads me to be guarded and prioritize self-preservation over building close relationships']);
big6.push([250000, 200000,'Stabil&shy;ity','This trait refers to the degree of emotional stability and reactivity in an individual. Neuroticism encompasses traits such as anxiety, moodiness, irritability, and susceptibility to stress. Highly neurotic individuals may experience negative emotions more intensely and frequently, whereas those low in neuroticism tend to be more emotionally stable and resilient.','','','','']);
big6.push([251000, 250000,'','','Being highly attuned to my emotions enables me to explore the depths of my feelings and gain valuable self-insight','A calm and resilient demeanor allows me to navigate life\'s challenges with composure and maintain a positive outlook','The heightened sensitivity to uncertainty and potential threats intensifies my emotional response, making me more prone to anxiety and stress','The motivation to avoid emotional turmoil and distress drives me to steer clear of situations that might trigger negative emotions, seeking stability and tranquility instead']);
big6.push([252000, 250000,'','','Being in touch with my emotions allows me to navigate and understand the complexities of human experience','Maintaining a calm and composed demeanor helps me cope with life\'s challenges and maintain emotional well-being','The fear of uncertainty and potential threats heightens my sensitivity to negative emotions, making me more prone to anxiety and stress','The fear of emotional turmoil and distress motivates me to avoid situations that may trigger negative emotions and seek stability and tranquility']);

////////////////////////////////////////
// Norsk
if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([2100000, -10, 'Big 5 Mini - personlighetstest', 'Big Five-personlighetstesten, ogs&aring; kjent som Femfaktormodellen (FFM), er en mye brukt ramme i psykologien for &aring; m&aring;le og beskrive personlighetstrekk. Disse trekkene betraktes som bredt dimensjoner av personlighet og brukes til &aring; beskrive og forst&aring; individuelle forskjeller i personlighetstrekk. Det er viktig &aring; merke seg at enkeltpersoner kan ha en kombinasjon av h&oslash;ye og lave scorer p&aring; hvert trekk, noe som resulterer i unike personlighetsprofiler.'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for milj&oslash;, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:']);

big6.push([2110000, 2100000, '&Aring;penhet for erfaring', 'Dette trekket gjenspeiler en persons tiltrekning mot nyhet, fantasi, kreativitet og intellektuell nysgjerrighet. Personer som er h&oslash;ye p&aring; &aring;penhet, har en tendens til &aring; v&aelig;re fantasifulle, &aring;pensinnede, eventyrlystne og sette pris p&aring; kunst og skj&oslash;nnhet. De som er lave p&aring; &aring;penhet, er mer konvensjonelle, praktiske og foretrekker rutine og kjennskap.', '', '', '', '']);
big6.push([2111000, 2110000, '', '', 'Endel&oslash;se muligheter inspirerer meg til &aring; utforske nye ideer og utfordre grensene for det som er kjent', 'Foretrekker &aring; holde meg til det jeg vet og f&oslash;ler meg komfortabel med, da det gir en f&oslash;lelse av sikkerhet og forutsigbarhet', '&Oslash;nsket om &aring; omfavne livets muligheter driver meg til stadig &aring; s&oslash;ke nye opplevelser og eventyr, og sikre at jeg ikke har noen angrende tanker', 'Usikkerheten rundt det ukjente hindrer meg i &aring; v&aring;ge utenfor komfortsonen og utforske nye ting']);
big6.push([2112000, 2110000, '', '', '&Aring; omfavne nye ideer og ukonvensjonell tenkning utvider perspektivet mitt og fremmer personlig vekst', 'Jeg finner tr&oslash;st i &aring; holde meg til kjente rutiner og etablerte metoder, da de gir en f&oslash;lelse av stabilitet og trygghet', 'V&aring;ge inn i uutforskede omr&aring;der gir n&aelig;ring til mitt &oslash;nske om kontinuerlig selvforbedring og oppdagelse', 'Frykten for det ukjente hindrer meg i &aring; tr&aring; utenfor komfortsonen og pr&oslash;ve nye ting']);
big6.push([2120000, 2100000, 'Samvittig&shy;hetsfullhet', 'Samvittighetsfullhet refererer til graden av organisasjon, ansvar, p&aring;litelighet og selvdisiplin hos en person. Personer med h&oslash;y samvittighetsfullhet er flittige, p&aring;litelige, organiserte og selvmotiverte, mens de som er lave p&aring; samvittighetsfullhet kan v&aelig;re mer spontane, avslappede og mindre opptatt av detaljer.', '', '', '', '']);
big6.push([2121000, 2120000, '', '', '&Aring; sette h&oslash;ye standarder og strebe etter ekspertise gj&oslash;r at jeg kan oppn&aring; bemerkelsesverdige resultater og n&aring; mitt fulle potensial', '&Aring; v&aelig;re mindre opptatt av detaljer og regler gir meg friheten til &aring; utforske ulike tiln&aelig;rminger og omfavne spontanitet', 'Motivasjonen for &aring; utmerke seg og m&oslash;te andres forventninger driver min besluttsomhet til &aring; planlegge og utf&oslash;re oppgaver feilfritt', 'Motviljen mot begrensninger og stive systemer gj&oslash;r meg motvillig til &aring; f&oslash;lge regler og overholde strenge tidsplaner']);
big6.push([2122000, 2120000, '', '', '&Aring; v&aelig;re organisert og detaljorientert gj&oslash;r at jeg kan holde styr p&aring; mine ansvarsomr&aring;der og oppn&aring; &oslash;nskede resultater', 'Jeg verdsetter fleksibilitet og spontanitet, da det gir meg muligheten til &aring; tilpasse meg og reagere effektivt p&aring; endrede omstendigheter', 'Streben etter perfeksjon og oppfyllelse av h&oslash;ye standarder driver meg til &aring; utmerke meg p&aring; ulike omr&aring;der i livet', 'Frykten for begrensninger og rigide strukturer gj&oslash;r at jeg motsetter meg &aring; f&oslash;lge regler og holde meg til strenge rutiner']);
big6.push([2130000, 2100000, 'Ekstro&shy;versjon', 'Dette trekket fanger opp en persons sosialitet, p&aring;g&aring;enhet, pratelyst og grad av utadvendthet. Utadvendte personer har en tendens til &aring; v&aelig;re energiske, entusiastiske og s&oslash;ke sosiale interaksjoner. De blir ofte beskrevet som utadvendte og f&aring;r energi av &aring; v&aelig;re sammen med andre. Introverte personer foretrekker derimot &aring; v&aelig;re alene, har en tendens til &aring; v&aelig;re mer reserverte og kan f&oslash;le seg utmattet av omfattende sosiale interaksjoner.', '', '', '', '']);
big6.push([2131000, 2130000, '', '', 'Spenningen ved sosiale interaksjoner og muligheten for nye forbindelser energiserer og inspirerer meg til stadig &aring; s&oslash;ke etter andre', 'Ensomhet og introspeksjon gir n&oslash;dvendig plass for &aring; utfolde min kreativitet og dykke dypere inn i mine tanker og ideer', '&Oslash;nsket om &aring; unng&aring; f&oslash;lelsen av ensomhet og frykten for &aring; g&aring; glipp av sosiale muligheter motiverer meg til stadig &aring; s&oslash;ke selskap av andre', 'Ubekvemheten knyttet til sosiale interaksjoner og overveldende stimuli f&aring;r meg til &aring; trekke meg tilbake og unng&aring; situasjoner som kan f&oslash;re til ubehag']);
big6.push([2132000, 2130000, '', '', '&Aring; engasjere seg i sosiale aktiviteter gir meg energi og hjelper meg &aring; trives i dynamiske og samarbeidsorienterte milj&oslash;er', 'Jeg finner tr&oslash;st i ensomhet og introspeksjon, som gir rom for selvrefleksjon og gjenopplading', 'Frykten for &aring; g&aring; glipp av sosiale muligheter driver meg til &aring; s&oslash;ke selskap av andre og engasjere meg i sosiale interaksjoner', 'Frykten for overveldende sosiale interaksjoner og stimuli f&aring;r meg til &aring; trekke meg tilbake og unng&aring; situasjoner som kan f&oslash;re til ubehag']);
big6.push([2140000, 2100000, 'Vennlighet', 'Vennlighet gjenspeiler en persons tendens til &aring; v&aelig;re medf&oslash;lende, samarbeidsvillig, empatisk og hensynsfull overfor andre. De som er h&oslash;ye p&aring; vennlighet er vanligvis vennlige, hjelpsomme, tillitsfulle og prioriterer harmoniske relasjoner. Personer som er lave p&aring; vennlighet kan v&aelig;re mer skeptiske, konkurransedyktige og p&aring;g&aring;ende.', '', '', '', '']);
big6.push([2141000, 2140000, '', '', 'Troen p&aring; samarbeid og medf&oslash;lelse motiverer meg til &aring; skape harmoni og ha en positiv innvirkning p&aring; andre', '&Aring; hevde mine egne behov og grenser gir meg friheten til &aring; forf&oslash;lge mine m&aring;l og &oslash;nsker uten &aring; f&oslash;le meg begrenset', '&Oslash;nsket om &aring; opprettholde harmoni og unng&aring; konflikt og misbilligelse motiverer meg til &aring; prioritere fredelige interaksjoner og unng&aring; konfrontasjoner', 'Tendensen til &aring; beskytte meg selv mot s&aring;rbarhet og avhengighet resulterer i forsiktighet og prioritering av selvbevaring fremfor &aring; danne n&aelig;re relasjoner']);
big6.push([2142000, 2140000, '', '', '&Aring; verdsette harmoni og empati gj&oslash;r at jeg kan bygge sterke og meningsfulle forbindelser med andre', '&Aring; hevde mine meninger og grenser gj&oslash;r det mulig for meg &aring; opprettholde min individualitet og personlig vekst', 'Frykten for konflikt og misbilligelse motiverer meg til &aring; prioritere &aring; opprettholde fred og unng&aring; konfrontasjoner', 'Frykten for s&aring;rbarhet og avhengighet f&oslash;rer til forsiktighet og prioritering av selvbevaring fremfor &aring; danne n&aelig;re relasjoner']);
big6.push([2150000, 2100000, 'Emosjonell stabilitet', 'Dette trekket refererer til graden av emosjonell stabilitet og reaktivitet hos en person. Neurotisisme omfatter trekk som angst, hum&oslash;rsvingninger, irritabilitet og s&aring;rbarhet for stress. Personer med h&oslash;y neurotisisme kan oppleve negative f&oslash;lelser mer intensivt og hyppigere, mens de som er lave p&aring; neurotisisme har en tendens til &aring; v&aelig;re mer emosjonelt stabile og motstandsdyktige.', '', '', '', '']);
big6.push([2151000, 2150000, '', '', '&Aring; v&aelig;re sterkt knyttet til mine f&oslash;lelser gj&oslash;r at jeg kan utforske dybden av mine f&oslash;lelser og f&aring; verdifull selvforst&aring;else', 'En rolig og motstandsdyktig v&aelig;rem&aring;te gj&oslash;r at jeg kan h&aring;ndtere utfordringene i livet med fatning og opprettholde et positivt syn p&aring; fremtiden', 'Den &oslash;kte f&oslash;lsomheten for usikkerhet og potensielle trusler intensiverer min emosjonelle respons og gj&oslash;r meg mer s&aring;rbar for angst og stress', 'Motivasjonen for &aring; unng&aring; emosjonell uro og lidelse f&aring;r meg til &aring; holde meg til kjente og trygge rutiner og situasjoner']);
big6.push([2152000, 2150000, '', '', 'Dyp refleksjon over mine f&oslash;lelser og indre tilstander gir meg innsikt og muligheten til &aring; vokse personlig og f&oslash;lelsesmessig', 'Evnen til &aring; holde meg rolig og h&aring;ndtere stressende situasjoner uten &aring; miste fatningen hjelper meg med &aring; opprettholde en balansert tilstand av sinnsro og velv&aelig;re', 'Den &oslash;kte s&aring;rbarheten for emosjonelle utfordringer gj&oslash;r meg oppmerksom p&aring; mine reaksjoner og gir meg muligheten til &aring; utvikle mestringsstrategier og st&oslash;tte', 'Tendensen til &aring; unng&aring; emosjonell uro og negativitet f&oslash;rer meg til &aring; holde meg til det kjente og forutsigbare']);

//////////////////////////////////////
// Biases
if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([2800000, -10, 'Biases', 'Biases to be extra aware of based upon your answers'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for miljø, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, miljø, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det ikke skjer:']);

big6.push([2810000, 2800000, 'Cognitive Biases', 'Cognitive biases are mental shortcuts or patterns that influence our judgment and decision-making. They can lead to errors and distortions in perception, memory, and reasoning. These biases often result from our brain\'s attempt to process information efficiently, but they can lead to suboptimal decisions and design choices.', '', '', '', '']);
big6.push([2811000, 2810000, 'Confirmation bias', 'Tendency to favor information that supports existing beliefs, ignoring contradictory evidence.', 'Refined decision-making, open-mindedness, and better solutions when challenging assumptions. ', ' Reduced stubbornness, greater adaptability, and embracing diverse perspectives. ', ' Reinforced misconceptions, hindered innovation, and suboptimal outcomes. ', ' Informed decisions, improved creativity, and greater objectivity.']);
big6.push([2812000, 2810000, 'Anchoring bias', 'Reliance on initial information to make decisions, affecting subsequent judgment regardless of accuracy.', 'Streamlined decision-making, avoiding fixation, and improved adaptability to new information. ', ' Less biased decisions, increased openness to alternative possibilities, and enhanced creativity. ', ' Limited exploration of alternatives, potential tunnel vision, and reduced adaptability. ', ' Diverse ideas, unbiased decisions, and improved problem-solving. ']);
big6.push([2813000, 2810000, 'Availability bias', 'Relying on readily available information, leading to the neglect of less accessible but relevant data.', 'Efficient decision-making, leveraging accessible insights, and faster problem-solving. ', ' Increased attention to overlooked information, reduced oversimplification, and more comprehensive solutions. ', ' Neglect of crucial data, limited perspective, and biased conclusions. ', ' Improved understanding, unbiased conclusions, and more balanced decisions. ']);
big6.push([2814000, 2810000, 'Overconfidence bias', 'Excessive belief in one\'s own judgments and abilities, often underestimating risks and potential errors.', 'Confidence in decisions, risk-taking, and self-assuredness in pursuing innovative ideas. ', ' Better recognition of limitations, increased humility, and more objective assessment of risks. ', ' Overestimated success, ignoring warning signs, and potential project failures. ', ' Realistic self-assessment, improved risk management, and increased team collaboration. ']);
big6.push([2815000, 2810000, 'Hindsight bias', 'Belief that an event was predictable after it occurred, leading to biased evaluations of past decisions.', 'Improved learning from experiences, building on past successes, and greater self-assurance. ', ' Enhanced objectivity in assessing past decisions, avoiding overconfidence, and promoting adaptability. ', ' Reinforcement of hindsight judgments, hindering innovation, and overlooking alternative approaches. ', ' Better foresight, embracing uncertainties, and promoting open-mindedness. ']);
big6.push([2820000, 2800000, 'Social, Cultural', 'Social and cultural biases arise from our interactions with others and the societal norms we internalize. These biases can affect design decisions by influencing our preferences, beliefs, and understanding of users. Recognizing and addressing these biases is crucial to creating inclusive and user-centered designs that resonate with diverse audiences.', '', '', '', '']);
big6.push([2821000, 2820000, 'User bias ', ' Assuming users are representative of the entire user base, neglecting diverse user needs and preferences. ', 'Personalized experiences for targeted users, efficient design solutions, and focused development. ', ' Inclusive design, catering to diverse user needs, and avoiding exclusion of specific user groups. ', ' Exclusion of important user segments, reduced market reach, and missed business opportunities. ', ' Empathy-driven design, broad market reach, and increased customer satisfaction. ']);
big6.push([2822000, 2820000, 'Designer bias ', ' Allowing personal preferences and assumptions to influence design decisions, potentially limiting creativity.', 'Unique design styles, showcasing designers\' identities, and distinguishing products from competitors. ', ' More diverse design approaches, avoiding design stereotypes, and fostering innovative solutions. ', ' Generic and biased designs, limited design diversity, and reduced user appeal. ', ' Inclusive design, enhanced creativity, and broader market acceptance. ']);
big6.push([2823000, 2820000, 'Cultural bias ', ' Designing with a single cultural perspective, disregarding the needs and values of other cultures. ', 'Targeted design for specific cultures, connecting with cultural norms, and enhancing brand loyalty. ', ' Culturally inclusive design, respecting diverse cultural sensitivities, and avoiding cultural misunderstandings. ', ' Cultural insensitivity, alienating certain user groups, and potential reputational damage. ', ' Increased cultural appreciation, reduced cultural friction, and broader international appeal. ']);
big6.push([2824000, 2820000, 'Groupthink ', ' Tendency to conform to group consensus, stifling diverse perspectives and critical thinking in decision-making.', 'Smooth collaboration, quick decision-making, and maintaining group cohesion. ', ' More open discussions, encouraging diverse ideas, and improved decision quality. ', ' Suppressed dissenting views, limiting creativity, and potential adoption of suboptimal solutions. ', ' Fostering constructive dissent, higher-quality decisions, and innovative solutions. ']);
big6.push([2825000, 2820000, 'Loss aversion bias ', ' Preferring avoiding losses over achieving gains, resulting in conservative design choices and missed opportunities.', 'Cautionary design, risk mitigation, and safeguarding against potential losses. ', ' Embracing strategic risks, pursuing innovative opportunities, and higher potential rewards. ', ' Missed chances for growth, stagnant designs, and lost opportunities for advancement. ', ' Bold design choices, embracing uncertainty, and seizing potential breakthroughs. ']);
big6.push([2830000, 2800000, 'Infor&shy;mation, Method', ' Information and method biases result from limitations in data collection, media influence, and design constraints. These biases can impact the quality of available information and the scope of design solutions. Overcoming these biases involves seeking diverse data sources, minimizing media manipulation, and creatively navigating design constraints.', '', '', '', '']);
big6.push([2831000, 2830000, 'Limited data access ', ' Insufficient access to relevant data, hindering comprehensive understanding and informed decision-making. ', 'Focused decision-making with available data, efficiency in data utilization, and avoiding information overload. ', ' In-depth insights from diverse data sources, supporting data-driven decisions, and deeper understanding. ', ' Incomplete understanding of the situation, potential data blind spots, and biased conclusions. ', ' More informed decisions, comprehensive insights, and higher data accuracy. ']);
big6.push([2832000, 2830000, 'Data sampling bias ', ' Bias introduced when data is collected in a way that does not accurately represent the entire population. ', 'Efficient data collection, cost-effective research, and practical implementation. ', ' Avoidance of skewed conclusions, comprehensive data representation, and fairer analysis. ', ' Misleading results, distorted insights, and biased conclusions drawn from data. ', ' Unbiased representation, improved data accuracy, and more reliable analysis. ']);
big6.push([2833000, 2830000, 'Media influence ', ' The media\'s impact on shaping opinions and perspectives, influencing design decisions and user perceptions. ', 'Wider audience reach, brand exposure, and effective communication through media channels. ', ' Avoidance of media-driven bias, critical analysis of media influence, and independent decision-making. ', ' Misleading user perceptions, biased brand portrayal, and potential misinformation spread. ', ' Independent user perspectives, authentic brand representation, and reduced media manipulation. ']);
big6.push([2834000, 2830000, 'Information overload ', ' Overwhelming users with excessive information, leading to reduced comprehension and decision-making abilities. ', 'Focused and concise information delivery, clarity in messaging, and reduced cognitive load. ', ' Prioritization of crucial information, avoiding user confusion, and better decision-making. ', ' Overlooked critical information, reduced user engagement, and inaccurate choices. ', ' Improved information assimilation, streamlined user experience, and enhanced user satisfaction. ']);
big6.push([2835000, 2830000, 'Design constraints and limitations ', ' Restrictive factors in the design process that may inhibit exploration of innovative solutions. ', 'Efficient resource utilization, faster development, and creative problem-solving under constraints. ', ' Potential inspiration from constraints, fostering innovative problem-solving, and unique design solutions. ', ' Stifled creativity, limited design exploration, and potential missed opportunities. ', ' Embracing design challenges, out-of-the-box thinking, and unique problem-solving. ']);
big6.push([2840000, 2800000, 'Emotional, Psycho&shy;logical', 'Emotional and psychological biases stem from our emotions, attitudes, and self-perceptions. They can influence how we perceive and interact with design elements. Understanding these biases is essential for creating emotionally engaging and empathetic designs that resonate with users on a deeper level.', '', '', '', '']);
big6.push([2841000, 2840000, 'Self-serving bias ', ' Tendency to attribute successes to internal factors while blaming failures on external factors. ', 'Enhanced self-motivation, positive mindset, and increased self-confidence in design endeavors. ', ' Improved acceptance of personal responsibility, self-awareness, and constructive self-improvement. ', ' Avoidance of accountability, hindered learning from failures, and potential stagnation. ', ' Greater accountability, objective self-evaluation, and continuous growth. ']);
big6.push([2842000, 2840000, 'Negativity bias ', ' Giving more weight to negative information and experiences, impacting user satisfaction and perception. ', 'Focused improvements based on negative feedback, increased empathy, and addressing user pain points. ', ' Balanced consideration of positive and negative feedback, improved emotional appeal, and enhanced UX. ', ' Negative impact on user satisfaction, diminished brand loyalty, and decreased user engagement. ', ' More positive user experiences, higher brand loyalty, and improved customer retention. ']);
big6.push([2843000, 2840000, 'Empathy gap ', ' Difficulty understanding and considering the emotions of others, affecting user-centered design approaches. ', 'Enhanced user empathy, better user-centric design, and products that cater to real user needs. ', ' Avoidance of design blind spots, inclusive and user-focused solutions, and increased user satisfaction. ', ' Detached design decisions, overlooking user emotions, and potential alienation of users. ', ' Empathetic design, stronger emotional connections, and increased user loyalty. ']);
big6.push([2844000, 2840000, 'Sunk cost fallacy ', ' Continuing an endeavor based on prior investments, even if it is no longer beneficial or relevant. ', 'Leveraging past investments efficiently, committing to projects with potential for turnaround. ', ' More rational decision-making, avoiding futile efforts, and pursuing better opportunities. ', ' Persistence in failing projects, wasted resources, and potential negative impacts on the organization. ', ' Resource optimization, agile project management, and improved ROI. ']);
big6.push([2845000, 2840000, 'Halo effect ', ' Allowing one positive trait to influence overall judgment positively, potentially overlooking flaws. ', 'Positive brand perception, increased customer loyalty, and potential premium pricing. ', ' Balanced assessment of strengths and weaknesses, better-informed judgments, and unbiased user opinions. ', ' Overvalued products, potential brand arrogance, and unaddressed product shortcomings. ', ' Objective user evaluation, product improvement, and potential competitive advantage. ']);
big6.push([2850000, 2800000, 'Deci&shy;sion&shy;making', 'Decision-making biases influence the choices we make in the design process. These biases can lead to suboptimal decisions, reluctance to embrace change, or irrational attachment to certain design features. Being aware of decision-making biases is crucial for fostering innovation and making user-centric choices.', '', '', '', '']);
big6.push([2851000, 2850000, 'Status quo bias ', ' Preferring to maintain the current state, avoiding change even if better alternatives are available. ', 'Stability in design choices, consistent user experience, and minimizing user disruption. ', ' Embracing change, pursuing innovation, and staying competitive with evolving trends. ', ' Stagnation in design, missed innovation opportunities, and potential loss of market relevance. ', ' Adaptive design, embracing new trends, and enhancing market competitiveness. ']);
big6.push([2852000, 2850000, 'Framing effect ', ' Different decisions resulting from how information is presented, emphasizing gains or losses. ', 'Leveraging framing to influence user decisions positively, enhancing marketing effectiveness. ', ' Neutral framing to promote unbiased decisions, improved transparency, and equitable user choices. ', ' Manipulative framing, biased information presentation, and potential user confusion. ', ' Transparent messaging, unbiased information, and more informed user decisions. ']);
big6.push([2853000, 2850000, 'Choice-supportive bias ', ' Post-decision belief that the chosen option is better than rejected alternatives, reinforcing satisfaction. ', 'Strengthened satisfaction with chosen options, reaffirming trust in design decisions. ', ' Avoidance of irrational attachment to chosen options, embracing potential improvements, and openness to change. ', ' Overconfidence in design decisions, limiting willingness to iterate, and overlooking potential enhancements. ', ' Continuous improvement, open-mindedness, and user-centric design iterations. ']);
big6.push([2854000, 2850000, 'Decision fatigue ', ' Reduced ability to make quality decisions after a series of choices, leading to suboptimal outcomes. ', 'Efficiently simplifying decision-making, optimizing user interfaces, and reducing cognitive load. ', ' Avoidance of overwhelming users, encouraging breaks in decision-making, and maintaining user engagement. ', ' Increased potential for user errors, decreased satisfaction, and potential abandonment of the process. ', ' Streamlined decision-making, improved accuracy, and better user satisfaction. ']);
big6.push([2855000, 2850000, 'Ambiguity aversion ', ' Preferring clear, certain options over ambiguous ones, potentially limiting exploration of new possibilities.', 'Simplified decision-making, avoiding complex choices, and reduced uncertainty. ', ' Embracing experimentation and innovation, exploring new solutions, and fostering creativity. ', ' Missed opportunities for innovation, limited creativity, and potential resistance to change. ', ' Enhanced creativity, exploration of possibilities, and openness to uncertainty. ']);
big6.push([2860000, 2800000, 'Tech&shy;nology, Interface', 'Technology and interface biases arise from our interactions with digital solutions. They include overdependence on technology, interface design\'s impact on user behavior, and the influence of algorithms on user experiences. Addressing these biases involves striking a balance between technology use, designing intuitive interfaces, and reducing algorithmic discrimination.', '', '', '', '']);
big6.push([2861000, 2860000, 'Automation bias ', ' Blindly trusting automated systems without verifying results, leading to potentially serious errors. ', 'Efficient reliance on reliable automation, increased productivity, and time savings. ', ' Avoidance of blind trust, vigilant monitoring of automated processes, and human intervention when needed. ', ' Overreliance on automation, potential complacency, and errors due to lack of human oversight. ', ' Balanced automation usage, human oversight, and error prevention. ']);
big6.push([2862000, 2860000, 'Interface bias ', ' The impact of interface design on user behavior and decision-making, influencing perceptions and choices. ', 'Positive user engagement, improved user interactions, and seamless navigation. ', ' Avoidance of biased interface designs, prioritizing usability, and catering to diverse user needs. ', ' Confusing interfaces, reduced user satisfaction, and potential abandonment of the platform. ', ' User-centric design, intuitive interfaces, and better user experiences. ']);
big6.push([2863000, 2860000, 'Algorithmic bias ', ' Prejudice resulting from biased algorithms, affecting recommendations and content served to users. ', 'Fair and inclusive algorithms, personalized content, and improved user experiences. ', ' Bias-free algorithms, avoiding discriminatory outputs, and providing equitable experiences for all users. ', ' Biased recommendations, discriminatory content, and potential harm to marginalized users. ', ' Unbiased algorithms, equitable user experiences, and reducing algorithmic discrimination. ']);
big6.push([2864000, 2860000, 'Technology overdependence ', ' Excessive reliance on technology, reducing critical thinking and user independence in decision-making. ', 'Excessive reliance on technology, reducing critical thinking and user independence in decision-making. ', ' Streamlined processes, increased efficiency, and leveraging technology\'s capabilities. ', ' Balanced use of technology, maintaining user autonomy, and considering human judgment in decisions. ', ' Limited critical thinking, reduced user autonomy, and potential technology failures. ']);
big6.push([2865000, 2860000, 'Feature fatigue ', ' Overwhelming users with too many features or options, leading to confusion and decreased engagement. ', 'Overambitious design disregards user needs, simplification aids UX, reduces waste, fosters inclusivity, and enhances user satisfaction.', 'User-centered approach avoids complexity, optimizes resources, enhances efficiency, promotes sustainable design, and elevates user experience.', 'Poor design decisions prioritize quantity over quality, leading to confusion, waste, frustration, and negative environmental impact.', 'Overlooking user needs hinders UX, increases digital clutter, wastes resources, and negatively impacts user satisfaction and the environment.']);
