// Free Space!

//if (big6.length == 0)
//    big6.push([0, -1, 'Test', '', '', '', '', '']);

//big6.push([300000, -10, 'Big 5 Mini - personlighetstest', 'Big Five-personlighetstesten, også kjent som Femfaktormodellen (FFM), er en mye brukt ramme i psykologien for å måle og beskrive personlighetstrekk. Disse trekkene betraktes som bredt dimensjoner av personlighet og brukes til å beskrive og forstå individuelle forskjeller i personlighetstrekk. Det er viktig å merke seg at enkeltpersoner kan ha en kombinasjon av høye og lave scorer på hvert trekk, noe som resulterer i unike personlighetsprofiler.'
//    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for miljø, samfunn og folk:'
//    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, miljø, samfunn og folk at det ikke skjer:'
//    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det skjer:'
//    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det ikke skjer:']);

//big6.push([310000,300000,'Åpenhet for erfaring','Dette trekket gjenspeiler en persons tiltrekning mot nyhet, fantasi, kreativitet og intellektuell nysgjerrighet. Personer som er høye på åpenhet, har en tendens til å være fantasifulle, åpensinnede, eventyrlystne og sette pris på kunst og skjønnhet. De som er lave på åpenhet, er mer konvensjonelle, praktiske og foretrekker rutine og kjennskap.','','','','']);
//big6.push([311000,310000,'','','Endeløse muligheter inspirerer meg til å utforske nye ideer og utfordre grensene for det som er kjent','Foretrekker å holde meg til det jeg vet og føler meg komfortabel med, da det gir en følelse av sikkerhet og forutsigbarhet','Ønsket om å omfavne livets muligheter driver meg til stadig å søke nye opplevelser og eventyr, og sikre at jeg ikke har noen angrende tanker','Usikkerheten rundt det ukjente hindrer meg i å våge utenfor komfortsonen og utforske nye ting']);
//big6.push([312000,310000,'','','Å omfavne nye ideer og ukonvensjonell tenkning utvider perspektivet mitt og fremmer personlig vekst','Jeg finner trøst i å holde meg til kjente rutiner og etablerte metoder, da de gir en følelse av stabilitet og trygghet','Våge inn i uutforskede områder gir næring til mitt ønske om kontinuerlig selvforbedring og oppdagelse','Frykten for det ukjente hindrer meg i å trå utenfor komfortsonen og prøve nye ting']);
//big6.push([320000,300000,'Samvittig&shy;hetsfullhet','Samvittighetsfullhet refererer til graden av organisasjon, ansvar, pålitelighet og selvdisiplin hos en person. Personer med høy samvittighetsfullhet er flittige, pålitelige, organiserte og selvmotiverte, mens de som er lave på samvittighetsfullhet kan være mer spontane, avslappede og mindre opptatt av detaljer.','','','','']);
//big6.push([321000,320000,'','','Å sette høye standarder og strebe etter ekspertise gjør at jeg kan oppnå bemerkelsesverdige resultater og nå mitt fulle potensial','Å være mindre opptatt av detaljer og regler gir meg friheten til å utforske ulike tilnærminger og omfavne spontanitet','Motivasjonen for å utmerke seg og møte andres forventninger driver min besluttsomhet til å planlegge og utføre oppgaver feilfritt','Motviljen mot begrensninger og stive systemer gjør meg motvillig til å følge regler og overholde strenge tidsplaner']);
//big6.push([322000,320000,'','','Å være organisert og detaljorientert gjør at jeg kan holde styr på mine ansvarsområder og oppnå ønskede resultater','Jeg verdsetter fleksibilitet og spontanitet, da det gir meg muligheten til å tilpasse meg og reagere effektivt på endrede omstendigheter','Streben etter perfeksjon og oppfyllelse av høye standarder driver meg til å utmerke meg på ulike områder i livet','Frykten for begrensninger og rigide strukturer gjør at jeg motsetter meg å følge regler og holde meg til strenge rutiner']);
//big6.push([330000,300000,'Ekstro&shy;versjon','Dette trekket fanger opp en persons sosialitet, pågåenhet, pratelyst og grad av utadvendthet. Utadvendte personer har en tendens til å være energiske, entusiastiske og søke sosiale interaksjoner. De blir ofte beskrevet som utadvendte og får energi av å være sammen med andre. Introverte personer foretrekker derimot å være alene, har en tendens til å være mer reserverte og kan føle seg utmattet av omfattende sosiale interaksjoner.','','','','']);
//big6.push([331000,330000,'','','Spenningen ved sosiale interaksjoner og muligheten for nye forbindelser energiserer og inspirerer meg til stadig å søke etter andre','Ensomhet og introspeksjon gir nødvendig plass for å utfolde min kreativitet og dykke dypere inn i mine tanker og ideer','Ønsket om å unngå følelsen av ensomhet og frykten for å gå glipp av sosiale muligheter motiverer meg til stadig å søke selskap av andre','Ubekvemheten knyttet til sosiale interaksjoner og overveldende stimuli får meg til å trekke meg tilbake og unngå situasjoner som kan føre til ubehag']);
//big6.push([332000,330000,'','','Å engasjere seg i sosiale aktiviteter gir meg energi og hjelper meg å trives i dynamiske og samarbeidsorienterte miljøer','Jeg finner trøst i ensomhet og introspeksjon, som gir rom for selvrefleksjon og gjenopplading','Frykten for å gå glipp av sosiale muligheter driver meg til å søke selskap av andre og engasjere meg i sosiale interaksjoner','Frykten for overveldende sosiale interaksjoner og stimuli får meg til å trekke meg tilbake og unngå situasjoner som kan føre til ubehag']);
//big6.push([340000,300000,'Vennlighet','Vennlighet gjenspeiler en persons tendens til å være medfølende, samarbeidsvillig, empatisk og hensynsfull overfor andre. De som er høye på vennlighet er vanligvis vennlige, hjelpsomme, tillitsfulle og prioriterer harmoniske relasjoner. Personer som er lave på vennlighet kan være mer skeptiske, konkurransedyktige og pågående.','','','','']);
//big6.push([341000,340000,'','','Troen på samarbeid og medfølelse motiverer meg til å skape harmoni og ha en positiv innvirkning på andre','Å hevde mine egne behov og grenser gir meg friheten til å forfølge mine mål og ønsker uten å føle meg begrenset','Ønsket om å opprettholde harmoni og unngå konflikt og misbilligelse motiverer meg til å prioritere fredelige interaksjoner og unngå konfrontasjoner','Tendensen til å beskytte meg selv mot sårbarhet og avhengighet resulterer i forsiktighet og prioritering av selvbevaring fremfor å danne nære relasjoner']);
//big6.push([342000,340000,'','','Å verdsette harmoni og empati gjør at jeg kan bygge sterke og meningsfulle forbindelser med andre','Å hevde mine meninger og grenser gjør det mulig for meg å opprettholde min individualitet og personlig vekst','Frykten for konflikt og misbilligelse motiverer meg til å prioritere å opprettholde fred og unngå konfrontasjoner','Frykten for sårbarhet og avhengighet fører til forsiktighet og prioritering av selvbevaring fremfor å danne nære relasjoner']);
//big6.push([350000,300000,'Emosjonell stabilitet','Dette trekket refererer til graden av emosjonell stabilitet og reaktivitet hos en person. Neurotisisme omfatter trekk som angst, humørsvingninger, irritabilitet og sårbarhet for stress. Personer med høy neurotisisme kan oppleve negative følelser mer intensivt og hyppigere, mens de som er lave på neurotisisme har en tendens til å være mer emosjonelt stabile og motstandsdyktige.','','','','']);
//big6.push([351000,350000,'','','Å være sterkt knyttet til mine følelser gjør at jeg kan utforske dybden av mine følelser og få verdifull selvforståelse','En rolig og motstandsdyktig væremåte gjør at jeg kan håndtere utfordringene i livet med fatning og opprettholde et positivt syn på fremtiden','Den økte følsomheten for usikkerhet og potensielle trusler intensiverer min emosjonelle respons og gjør meg mer sårbar for angst og stress','Motivasjonen for å unngå emosjonell uro og lidelse får meg til å holde meg til kjente og trygge rutiner og situasjoner']);
//big6.push([352000,350000,'','','Dyp refleksjon over mine følelser og indre tilstander gir meg innsikt og muligheten til å vokse personlig og følelsesmessig','Evnen til å holde meg rolig og håndtere stressende situasjoner uten å miste fatningen hjelper meg med å opprettholde en balansert tilstand av sinnsro og velvære','Den økte sårbarheten for emosjonelle utfordringer gjør meg oppmerksom på mine reaksjoner og gir meg muligheten til å utvikle mestringsstrategier og støtte','Tendensen til å unngå emosjonell uro og negativitet fører meg til å holde meg til det kjente og forutsigbare']);
