if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([400000, 1, 'Job Candidate', 'Evaluating candidates based on their responses to these statements can provide valuable insights into their mindset, skills, and adaptability. Remember to use these statements as part of a larger evaluation process to make well-rounded hiring decisions.'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for miljø, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, miljø, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det ikke skjer:']);

big6.push([410000,400000,'Technical Skills','Technical skills refer to a candidate\'s proficiency in specific tools, technologies, and methodologies relevant to their field of expertise. These abilities enable individuals to execute tasks effectively, demonstrate expertise, and adapt to changing technological landscapes. Proficiency in programming languages, software applications, data analysis, and other technical competencies are crucial for success in various roles, from software development to engineering and beyond.','','','','']);
big6.push([411000,410000,'','',' I am excited about exploring new technologies and finding innovative ways to apply them in my work. ',' I have limited experience with the specific tools and technologies required for this job, but I\'m eager to learn. ',' I prefer to stick to the technologies and tools I\'m already familiar with rather than experimenting with unfamiliar ones. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([412000,410000,'','',' I believe in continuous learning and am always eager to acquire new technical skills to stay ahead in my field. ',' While I lack expertise in certain technical areas, I am confident in my ability to adapt and grow. ',' I feel more comfortable relying on my existing expertise rather than investing time in learning new technical skills. ',' I feel uncomfortable taking on projects that demand technical expertise beyond my current abilities. ']);
big6.push([420000,400000,'Problem-Solving and Critical Thinking','Problem-solving and critical thinking encompass a candidate\'s ability to analyze complex issues, identify viable solutions, and make informed decisions. These skills involve gathering information, evaluating alternatives, and considering potential consequences to reach optimal conclusions. Candidates who exhibit strong problem-solving and critical thinking skills demonstrate adaptability, creativity, and a capacity to handle challenges effectively in various work scenarios.','','','','']);
big6.push([421000,420000,'','',' I enjoy taking on complex challenges, as they provide opportunities for creative problem-solving and personal growth. ',' I am not always confident in my problem-solving abilities but enjoy challenging myself to find solutions. ',' When faced with complex problems, I tend to look for established solutions and avoid taking unnecessary risks. ',' I struggle with solving complex problems and often seek others\' help to overcome challenges. ']);
big6.push([422000,420000,'','',' I believe that trying new approaches, even if they carry some uncertainty, can lead to breakthrough solutions. ',' While I may lack experience in handling complex problems, I\'m willing to invest effort to improve. ',' I am cautious about experimenting with unproven problem-solving methods, as I fear the potential for failure. ',' I tend to avoid tackling complex problems, as I fear making mistakes or reaching ineffective solutions. ']);
big6.push([430000,400000,'Communication and Interpersonal Skills','Communication and interpersonal skills encompass a candidate\'s capacity to convey ideas clearly, actively listen, and collaborate effectively with team members. Strong communication fosters a positive work environment and promotes successful teamwork, project execution, and client relationships. It involves articulating thoughts, providing constructive feedback, and resolving conflicts while maintaining respect and understanding.','','','','']);
big6.push([431000,430000,'','',' I value open communication and actively seek out opportunities to collaborate and share ideas with my team. ',' I find it challenging to express my ideas clearly but am open to feedback and opportunities to improve. ',' In group settings, I prefer to listen and observe rather than actively contribute, to avoid saying the wrong thing. ',' I often hesitate to engage in open communication due to my fear of miscommunication or conflict. ']);
big6.push([432000,430000,'','',' I enjoy participating in group discussions and feel energized by exchanging thoughts and perspectives. ',' Though I lack confidence in group discussions, I am willing to work on my communication skills. ',' I sometimes find it challenging to express my ideas openly in fear of potential misunderstandings. ',' I tend to avoid participating in group discussions, fearing that I may say the wrong things. ']);
big6.push([440000,400000,'Cultural Fit and Personality Assessment','Cultural fit and personality assessment involve evaluating a candidate\'s alignment with the organization\'s values, mission, and work environment. Assessing cultural fit ensures potential employees will thrive within the company\'s ethos, enhancing team dynamics and overall productivity. Personality traits, such as adaptability, emotional intelligence, and collaboration, are also essential indicators of how candidates will integrate into the company\'s culture.','','','','']);
big6.push([441000,440000,'','',' I believe that taking calculated risks can lead to significant rewards and foster a culture of innovation. ',' I may not be fully comfortable with risk-taking, but I\'m open to learning and adapting to a dynamic culture. ',' I prefer a stable and predictable work environment where the focus is on maintaining the status quo. ',' I am risk-averse and may struggle to align with a culture that values taking calculated risks. ']);
big6.push([442000,440000,'','',' I am enthusiastic about working in a dynamic environment that encourages employees to explore new possibilities. ',' While I\'m not the most innovative person, I believe I can contribute positively to a culture that fosters growth. ',' I tend to be cautious when it comes to embracing changes, as they may introduce unforeseen risks. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ']);
big6.push([450000,400000,'Long-Term Goals and Motivation','Long-term goals and motivation refer to a candidate\'s aspirations and determination to achieve personal and professional objectives. Candidates with clear and ambitious long-term goals demonstrate a commitment to growth and self-improvement, indicating a higher potential for contributing positively to the organization. Motivated individuals possess the drive and resilience to pursue their objectives, leading to higher levels of productivity and engagement.','','','','']);
big6.push([451000,450000,'','',' I am motivated by the opportunity to make a meaningful impact and create positive change in my career. ',' I have not yet fully defined my long-term career goals but am open to exploring various possibilities. ',' I prefer not to set ambitious long-term goals, as I fear failure or not being able to achieve them. ',' I don\'t pay much attention to industry trends, as I prefer to rely on my existing knowledge and methods. ']);
big6.push([452000,450000,'','',' Setting ambitious goals excites me, and I am driven to push my boundaries and achieve extraordinary outcomes. ',' While I lack clarity in my long-term goals, I\'m motivated to discover my passion and pursue it. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ',' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ']);
big6.push([460000,400000,'Industry Knowledge and Trends','Industry knowledge and trends encompass a candidate\'s awareness of current developments, advancements, and market dynamics within their respective field. Staying up-to-date with industry trends showcases a candidate\'s dedication to continuous learning and adaptability to changing demands. A thorough understanding of industry best practices and emerging technologies positions individuals to make informed decisions and stay competitive in their professional domain','','','','']);
big6.push([461000,460000,'','',' I keep myself updated on industry trends and emerging technologies to identify new opportunities for growth. ',' I might not be up-to-date with all the recent industry trends, but I\'m eager to stay informed and learn. ',' I am cautious about changes in the industry and prefer to rely on established practices to avoid risks. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([462000,460000,'','',' I enjoy exploring potential disruptions in the industry, as they may lead to untapped possibilities. ',' While I lack in-depth knowledge of current industry trends, I\'m curious to explore and understand them better. ',' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ',' I tend to be skeptical about the long-term impact of emerging trends until they prove their worth. ']);