if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([400000, 0, 'Job Candidate', 'Evaluating candidates based on their responses to these statements can provide valuable insights into their mindset, skills, and adaptability. Remember to use these statements as part of a larger evaluation process to make well-rounded hiring decisions.'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for miljø, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, miljø, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, miljø, samfunn og folk at det ikke skjer:']);

big6.push([410000, 400000,'Technical Skills','Technical skills refer to a candidate\'s proficiency in specific tools, technologies, and methodologies relevant to their field of expertise. These abilities enable individuals to execute tasks effectively, demonstrate expertise, and adapt to changing technological landscapes. Proficiency in programming languages, software applications, data analysis, and other technical competencies are crucial for success in various roles, from software development to engineering and beyond.','','','','']);
big6.push([411000, 410000,'','',' I am excited about exploring new technologies and finding innovative ways to apply them in my work. ',' I have limited experience with the specific tools and technologies required for this job, but I\'m eager to learn. ',' I prefer to stick to the technologies and tools I\'m already familiar with rather than experimenting with unfamiliar ones. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([412000, 410000,'','',' I believe in continuous learning and am always eager to acquire new technical skills to stay ahead in my field. ',' While I lack expertise in certain technical areas, I am confident in my ability to adapt and grow. ',' I feel more comfortable relying on my existing expertise rather than investing time in learning new technical skills. ',' I feel uncomfortable taking on projects that demand technical expertise beyond my current abilities. ']);
big6.push([420000, 400000,'Problem-Solving and Critical Thinking','Problem-solving and critical thinking encompass a candidate\'s ability to analyze complex issues, identify viable solutions, and make informed decisions. These skills involve gathering information, evaluating alternatives, and considering potential consequences to reach optimal conclusions. Candidates who exhibit strong problem-solving and critical thinking skills demonstrate adaptability, creativity, and a capacity to handle challenges effectively in various work scenarios.','','','','']);
big6.push([421000, 420000,'','',' I enjoy taking on complex challenges, as they provide opportunities for creative problem-solving and personal growth. ',' I am not always confident in my problem-solving abilities but enjoy challenging myself to find solutions. ',' When faced with complex problems, I tend to look for established solutions and avoid taking unnecessary risks. ',' I struggle with solving complex problems and often seek others\' help to overcome challenges. ']);
big6.push([422000, 420000,'','',' I believe that trying new approaches, even if they carry some uncertainty, can lead to breakthrough solutions. ',' While I may lack experience in handling complex problems, I\'m willing to invest effort to improve. ',' I am cautious about experimenting with unproven problem-solving methods, as I fear the potential for failure. ',' I tend to avoid tackling complex problems, as I fear making mistakes or reaching ineffective solutions. ']);
big6.push([430000, 400000,'Communication and Interpersonal Skills','Communication and interpersonal skills encompass a candidate\'s capacity to convey ideas clearly, actively listen, and collaborate effectively with team members. Strong communication fosters a positive work environment and promotes successful teamwork, project execution, and client relationships. It involves articulating thoughts, providing constructive feedback, and resolving conflicts while maintaining respect and understanding.','','','','']);
big6.push([431000, 430000,'','',' I value open communication and actively seek out opportunities to collaborate and share ideas with my team. ',' I find it challenging to express my ideas clearly but am open to feedback and opportunities to improve. ',' In group settings, I prefer to listen and observe rather than actively contribute, to avoid saying the wrong thing. ',' I often hesitate to engage in open communication due to my fear of miscommunication or conflict. ']);
big6.push([432000, 430000,'','',' I enjoy participating in group discussions and feel energized by exchanging thoughts and perspectives. ',' Though I lack confidence in group discussions, I am willing to work on my communication skills. ',' I sometimes find it challenging to express my ideas openly in fear of potential misunderstandings. ',' I tend to avoid participating in group discussions, fearing that I may say the wrong things. ']);
big6.push([440000, 400000,'Cultural Fit and Personality Assessment','Cultural fit and personality assessment involve evaluating a candidate\'s alignment with the organization\'s values, mission, and work environment. Assessing cultural fit ensures potential employees will thrive within the company\'s ethos, enhancing team dynamics and overall productivity. Personality traits, such as adaptability, emotional intelligence, and collaboration, are also essential indicators of how candidates will integrate into the company\'s culture.','','','','']);
big6.push([441000, 440000,'','',' I believe that taking calculated risks can lead to significant rewards and foster a culture of innovation. ',' I may not be fully comfortable with risk-taking, but I\'m open to learning and adapting to a dynamic culture. ',' I prefer a stable and predictable work environment where the focus is on maintaining the status quo. ',' I am risk-averse and may struggle to align with a culture that values taking calculated risks. ']);
big6.push([442000, 440000,'','',' I am enthusiastic about working in a dynamic environment that encourages employees to explore new possibilities. ',' While I\'m not the most innovative person, I believe I can contribute positively to a culture that fosters growth. ',' I tend to be cautious when it comes to embracing changes, as they may introduce unforeseen risks. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ']);
big6.push([450000, 400000,'Long-Term Goals and Motivation','Long-term goals and motivation refer to a candidate\'s aspirations and determination to achieve personal and professional objectives. Candidates with clear and ambitious long-term goals demonstrate a commitment to growth and self-improvement, indicating a higher potential for contributing positively to the organization. Motivated individuals possess the drive and resilience to pursue their objectives, leading to higher levels of productivity and engagement.','','','','']);
big6.push([451000, 450000,'','',' I am motivated by the opportunity to make a meaningful impact and create positive change in my career. ',' I have not yet fully defined my long-term career goals but am open to exploring various possibilities. ',' I prefer not to set ambitious long-term goals, as I fear failure or not being able to achieve them. ',' I don\'t pay much attention to industry trends, as I prefer to rely on my existing knowledge and methods. ']);
big6.push([452000, 450000,'','',' Setting ambitious goals excites me, and I am driven to push my boundaries and achieve extraordinary outcomes. ',' While I lack clarity in my long-term goals, I\'m motivated to discover my passion and pursue it. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ',' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ']);
big6.push([460000, 400000,'Industry Knowledge and Trends','Industry knowledge and trends encompass a candidate\'s awareness of current developments, advancements, and market dynamics within their respective field. Staying up-to-date with industry trends showcases a candidate\'s dedication to continuous learning and adaptability to changing demands. A thorough understanding of industry best practices and emerging technologies positions individuals to make informed decisions and stay competitive in their professional domain','','','','']);
big6.push([461000, 460000,'','',' I keep myself updated on industry trends and emerging technologies to identify new opportunities for growth. ',' I might not be up-to-date with all the recent industry trends, but I\'m eager to stay informed and learn. ',' I am cautious about changes in the industry and prefer to rely on established practices to avoid risks. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([462000, 460000, '', '', ' I enjoy exploring potential disruptions in the industry, as they may lead to untapped possibilities. ', ' While I lack in-depth knowledge of current industry trends, I\'m curious to explore and understand them better. ', ' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ', ' I tend to be skeptical about the long-term impact of emerging trends until they prove their worth. ']);

////////////////////////////////////////////////////////////////////////////////
// Norsk kandidattest
if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([500000, -10, 'Norsk kandidattest', 'Kandidattest er designet for å indikere ferdighetsvurdering'
    , 'Explain in 20 words or less why this discribes you, and how this is a good thing:'
    , 'Explain in 20 words or less why this does not discribe the person tested, and how it is a good thing not to have this trait:'
    , 'Explain in 20 words or less why this discribes you, and how this is not a good thing:'
    , 'Explain in 20 words or less why this does not discribe the person tested, and how it is a bad thing not to have this trait:']);

big6.push([4510000, 4500000, 'Tek&shy;nikk', 'Teknisk ferdighetsvurdering omfatter en kandidats innstilling til kompetanse innen spesifikke verktøy, teknologier og metoder som er relevante for deres ekspertiseområde. Disse ferdighetene gjør individene i stand til å utføre oppgaver effektivt, demonstrere ekspertise og tilpasse seg skiftende teknologiske landskap. Beherskelse av programmeringsspråk, programvareapplikasjoner, dataanalyse og andre tekniske kompetanser er avgjørende for suksess i ulike roller, fra programvareutvikling til ingeniørfag og videre.', '', '', '', '']);
big6.push([4511000, 4510000, '', '', ' Jeg gleder meg til å utforske nye teknologier og finne innovative måter å anvende dem i arbeidet mitt. ', ' Jeg har begrenset erfaring med de spesifikke verktøyene og teknologiene som kreves for denne jobben, men jeg er ivrig etter å lære. ', ' Jeg foretrekker å holde meg til teknologiene og verktøyene jeg allerede er kjent med, heller enn å eksperimentere med ukjente. ', ' Jeg har liten eller ingen erfaring med de nødvendige tekniske ferdighetene, og jeg nøler med å skaffe dem. ']);
big6.push([4512000, 4510000, '', '', ' Jeg tror på kontinuerlig læring og er alltid ivrig etter å skaffe nye tekniske ferdigheter for å holde meg oppdatert. ', ' Selv om jeg mangler ekspertise på visse tekniske områder, er jeg trygg på min evne til å tilpasse meg og vokse. ', ' Jeg føler meg mer komfortabel med å stole på min eksisterende ekspertise i stedet for å investere tid i å lære nye tekniske ferdigheter. ', ' Jeg føler meg ukomfortabel med å ta på meg prosjekter som krever tekniske ferdigheter utover mine nåværende evner. ']);
big6.push([4513000, 4510001, '', '', ' Mine tekniske ferdigheter er et styrkeområde, og jeg er alltid på utkikk etter muligheter for å bruke dem til å løse utfordringer. ', ' Selv om jeg har begrenset erfaring med noen teknologier, er jeg sikker på at jeg kan lære raskt og effektivt. ', ' Jeg fokuserer primært på ikke-tekniske aspekter av jobben min og foretrekker å delegere tekniske oppgaver til andre. ', ' Mine tekniske ferdigheter er begrensede, og jeg har liten interesse for å utvide dem. ']);
big6.push([4514000, 4510002, '', '', ' Jeg har erfaring med et bredt spekter av teknologier og føler meg komfortabel med å håndtere komplekse tekniske utfordringer. ', ' Mine tekniske ferdigheter er ikke helt oppdaterte, men jeg har en plan for å forbedre dem gjennom kurs og opplæring. ', ' Jeg fokuserer hovedsakelig på det jeg allerede kan, og jeg er skeptisk til å prøve nye teknologier som kan innebære risiko. ', ' Mine tekniske ferdigheter er utilstrekkelige for å møte kravene i denne stillingen, og jeg tviler på min evne til å utvikle dem tilstrekkelig. ']);
big6.push([4515000, 4510003, '', '', ' Jeg ser på tekniske utfordringer som spennende muligheter for å lære og utvikle meg, og jeg tar initiativ til å forbedre mine ferdigheter. ', ' Jeg har ikke mye erfaring med de spesifikke tekniske verktøyene som brukes i denne stillingen, men jeg har tro på min evne til å mestre dem. ', ' Jeg er tilfreds med min nåværende tekniske kompetanse og føler ingen behov for å utvide den ytterligere. ', ' Mine tekniske ferdigheter er begrensede, og jeg er usikker på om jeg noensinne vil kunne bli dyktig innen dette området. ']);
big6.push([4520000, 4500000, 'Løs&shy;ning', 'Problemløsning og kritisk tenking omfatter en kandidats evne til å analysere komplekse problemstillinger, identifisere levedyktige løsninger og fatte informerte beslutninger. Disse ferdighetene innebærer å samle informasjon, vurdere alternativer og vurdere potensielle konsekvenser for å nå optimale konklusjoner. Kandidater som viser sterke problemløsnings- og kritisk tenkningsevner, demonstrerer evnen til å tilpasse seg, kreativitet og evne til å håndtere utfordringer effektivt i ulike arbeidssituasjoner.', '', '', '', '']);
big6.push([4521000, 4520000, '', '', ' Jeg liker å ta på meg komplekse utfordringer, da de gir muligheter for kreativ problemløsning og personlig vekst. ', ' Jeg er ikke alltid trygg på mine problemløsningsevner, men jeg liker å utfordre meg selv for å finne løsninger. ', ' Når jeg står overfor komplekse problemer, har jeg en tendens til å se etter etablerte løsninger og unngå unødvendige risikoer. ', ' Jeg sliter med å løse komplekse problemer og søker ofte hjelp fra andre for å overkomme utfordringer. ']);
big6.push([4522000, 4520000, '', '', ' Jeg tror at å prøve nye tilnærminger, selv om de innebærer noe usikkerhet, kan føre til gjennombruddsløsninger. ', ' Selv om jeg mangler erfaring med å håndtere komplekse problemer, er jeg villig til å investere innsats for å forbedre meg. ', ' Jeg er forsiktig med å eksperimentere med uprøvde problemløsningsmetoder, da jeg frykter muligheten for feil. ', ' Jeg unngår å takle komplekse problemer, da jeg frykter feil eller ineffektive løsninger. ']);
big6.push([4523000, 4520000, '', '', ' Jeg trives med utfordringer og ser på dem som muligheter for å utvikle mine problemløsningsevner. ', ' Selv om jeg ikke alltid føler meg trygg i komplekse situasjoner, motiverer det meg til å lære og forbedre meg. ', ' Jeg foretrekker å overlate problemløsning til andre og fokusere på mine egne ansvarsområder. ', ' Jeg har liten tillit til mine evner til å løse komplekse problemer, og jeg unngår ofte slike situasjoner. ']);
big6.push([4524000, 4520000, '', '', ' Jeg ser på problemløsning som en essensiell del av jobben min, og jeg søker stadig nye måter å forbedre arbeidsprosesser på. ', ' Selv om jeg ikke alltid har løsningsalternativer klare, er jeg villig til å konsultere kolleger og samarbeide for å finne de beste løsningene. ', ' Jeg følger vanligvis etablerte metoder for problemløsning, da jeg foretrekker å unngå risikofylte eksperimenter. ', ' Jeg har vanskelig for å takle komplekse problemer alene, og jeg blir ofte overveldet av slike utfordringer. ']);
big6.push([4525000, 4520000, '', '', ' Jeg føler meg komfortabel med å utforske flere alternativer når jeg løser problemer, og jeg er ikke redd for å ta risikoer hvis det er nødvendig. ', ' Jeg kan føle meg usikker når jeg står overfor komplekse problemer, men jeg vet at jeg kan lære og forbedre mine ferdigheter. ', ' Jeg er motvillig til å forlate kjente løsninger, da jeg frykter at ukjente metoder kan føre til feil eller forsinkelser. ', ' Jeg har liten tro på mine problemløsningsevner, og jeg foretrekker å søke hjelp fra andre i stedet for å ta på meg utfordringer selv. ']);
big6.push([4530000, 4500000, 'For&shy;mid&shy;le', 'Kommunikasjon og interpersonlige ferdigheter omfatter en kandidats evne til å formidle ideer klart, lytte aktivt og samarbeide effektivt med teammedlemmer. Sterk kommunikasjon fremmer et positivt arbeidsmiljø og bidrar til vellykket teamwork, prosjektutførelse og kundeforhold. Det innebærer å uttrykke tanker, gi konstruktiv tilbakemelding og løse konflikter samtidig som respekt og forståelse opprettholdes.', '', '', '', '']);
big6.push([4531000, 4530000, '', '', ' Jeg verdsetter åpen kommunikasjon og søker aktivt muligheter for samarbeid og deling av ideer med teamet mitt. ', ' Jeg synes det kan være utfordrende å uttrykke ideene mine klart, men jeg er åpen for tilbakemeldinger og muligheter for forbedring. ', ' I gruppesammenhenger foretrekker jeg å lytte og observere i stedet for å aktivt bidra, for å unngå å si noe feil. ', ' Jeg nøler ofte med å engasjere meg i åpen kommunikasjon på grunn av frykt for misforståelser eller konflikter. ']);
big6.push([4532000, 4530000, '', '', ' Jeg trives med å delta i gruppediskusjoner og føler meg engasjert av å utveksle tanker og perspektiver. ', ' Selv om jeg mangler selvtillit i gruppediskusjoner, er jeg villig til å arbeide med mine kommunikasjonsevner. ', ' Jeg har av og til problemer med å uttrykke ideene mine åpent av frykt for potensielle misforståelser. ', ' Jeg unngår å delta i gruppediskusjoner, da jeg frykter at jeg kan si noe feil. ']);
big6.push([4533000, 4530000, '', '', ' Jeg tror at tydelig kommunikasjon er en nøkkel til vellykket samarbeid, og jeg tar initiativ til å bidra til diskusjoner. ', ' Selv om jeg har noen utfordringer med kommunikasjon, tar jeg aktivt del i teammøter for å forbedre mine ferdigheter. ', ' Jeg er mer komfortabel med å kommunisere skriftlig enn muntlig, og jeg unngår ofte gruppediskusjoner. ', ' Jeg har lav selvtillit når det kommer til kommunikasjon, og jeg føler meg ofte usynlig i gruppesammenhenger. ']);
big6.push([4534000, 4530000, '', '', ' Jeg er trygg på mine kommunikasjonsevner, og jeg er åpen for å gi og motta konstruktiv tilbakemelding for å forbedre meg. ', ' Selv om jeg noen ganger kan føle meg usikker på mine kommunikasjonsevner, er jeg villig til å ta sjanser for å uttrykke mine ideer. ', ' Jeg unngår ofte konflikter ved å ikke uttrykke mine meninger eller bekymringer i gruppesammenhenger. ', ' Jeg er redd for å uttrykke mine meninger, da jeg frykter at de vil bli avvist av andre. ']);
big6.push([4535000, 4530000, '', '', ' Jeg tror på åpen og ærlig kommunikasjon, og jeg tar initiativ til å skape en inkluderende atmosfære i teamet mitt. ', ' Selv om jeg noen ganger kan være reservert i gruppesammenhenger, prøver jeg å utvikle mine kommunikasjonsevner gjennom praksis. ', ' Jeg er tilbakeholden med å uttrykke mine tanker og ideer, da jeg er redd for å bli kritisert av mine kolleger. ', ' Jeg unngår å ta på meg oppgaver som krever sterk kommunikasjonsevne, da jeg er usikker på mine evner på dette området. ']);
big6.push([4540000, 4500000, 'Kul&shy;tur', 'Kultur og personlighetsvurdering innebærer å vurdere i hvilken grad en kandidat passer inn i organisasjonens verdier, mål og arbeidsmiljø. Å vurdere kulturell tilpasning sikrer at potensielle ansatte vil trives i samsvar med bedriftens etos og forbedrer teamdynamikk og produktivitet. Personlighetstrekk som tilpasningsdyktighet, emosjonell intelligens og samarbeidsevner er også viktige indikatorer på hvordan kandidater vil integrere seg i bedriftens kultur.', '', '', '', '']);
big6.push([4541000, 4540000, '', '', ' Jeg tror at å ta kalkulerte risikoer kan føre til betydelige belønninger og fremme en kultur for innovasjon. ', ' Jeg er kanskje ikke helt komfortabel med risikotaking, men jeg er åpen for læring og tilpasning til en dynamisk kultur. ', ' Jeg foretrekker en stabil og forutsigbar arbeidsmiljø der fokus er på å opprettholde status quo. ', ' Jeg er risikoavers og kan ha problemer med å tilpasse meg en kultur som verdsetter kalkulerte risikoer. ']);
big6.push([4542000, 4540000, '', '', ' Jeg er entusiastisk med å jobbe i en dynamisk arbeidsmiljø som oppmuntrer ansatte til å utforske nye muligheter. ', ' Selv om jeg ikke regnes som den mest innovative personen, tror jeg at jeg kan bidra positivt til en kultur for kontinuerlig forbedring. ', ' Jeg er forsiktig med å omfavne endringer i bransjen, da de kan introdusere uforutsette risikoer. ', ' Jeg foretrekker en arbeidsmiljø der risikotaking er minimal, og jeg er skeptisk til endringer som kan forstyrre stabiliteten. ']);
big6.push([4543000, 4540000, '', '', ' Jeg verdsetter en kultur for samarbeid og gjensidig støtte, der ideer blir delt og kolleger støtter hverandre. ', ' Selv om jeg noen ganger kan føle meg ut av komfortsonen, søker jeg å tilpasse meg og bidra positivt til et teammiljø. ', ' Jeg er mer komfortabel med å jobbe uavhengig og trives med å løse oppgaver på egen hånd. ', ' Jeg har vanskelig for å tilpasse meg et samarbeidsorientert arbeidsmiljø, da jeg trives bedre alene. ']);
big6.push([4544000, 4540000, '', '', ' Jeg ser på en positiv arbeidskultur som essensiell for trivsel og suksess, og jeg prøver å spre positivitet rundt meg. ', ' Selv om jeg ikke alltid er den mest utadvendte personen, setter jeg pris på en positiv arbeidskultur og ønsker å bidra til den. ', ' Jeg kan være reservert og motvillig til å engasjere meg i å bygge en positiv arbeidskultur. ', ' Jeg føler meg ikke som en god kulturell match for arbeidsmiljøet, og jeg kan ha problemer med å tilpasse meg til bedriftens verdier. ']);
big6.push([4545000, 4540000, '', '', ' Jeg tror på å bygge et inkluderende arbeidsmiljø der forskjellige perspektiver blir verdsatt og feiret. ', ' Selv om jeg ikke alltid er den mest sosiale personen, søker jeg å respektere og forstå mine kollegers ulike perspektiver. ', ' Jeg er tilbakeholden med å inkludere andre i beslutningsprosesser, da jeg foretrekker å jobbe selvstendig. ', ' Jeg tror ikke at jeg passer godt inn i arbeidsmiljøet, og jeg føler meg ofte isolert fra teamet mitt. ']);
big6.push([4550000, 4500000, 'Lang&shy;sik&shy;tig', 'Langsiktige mål og motivasjon refererer til en kandidats aspirasjoner og vilje til å oppnå personlige og faglige mål. Kandidater med klare og ambisiøse langsiktige mål demonstrerer forpliktelse til vekst og selvforbedring, noe som indikerer høy potensial for å bidra positivt til organisasjonen. Motiverte individer besitter drivkraft og utholdenhet for å forfølge målene sine, noe som fører til høyere produktivitet og engasjement.', '', '', '', '']);
big6.push([4551000, 4550000, '', '', ' Jeg blir motivert av muligheten til å gjøre en meningsfylt innvirkning og skape positiv endring i karrieren min. ', ' Jeg har ennå ikke fullstendig definert mine langsiktige karrieremål, men jeg er åpen for å utforske ulike muligheter. ', ' Jeg foretrekker å ikke sette ambisiøse langsiktige mål, da jeg frykter at jeg kan mislykkes eller ikke kunne oppnå dem. ', ' Jeg bryr meg ikke mye om bransjetrender, da jeg foretrekker å stole på min eksisterende kunnskap og metoder. ']);
big6.push([4552000, 4550000, '', '', ' Å sette ambisiøse mål inspirerer meg, og jeg er drevet til å utfordre mine grenser og oppnå ekstraordinære resultater. ', ' Selv om jeg mangler klarhet i mine langsiktige mål, er jeg motivert for å oppdage min lidenskap og forfølge den. ', ' Jeg unngår å tenke på langsiktige mål, da jeg foretrekker å fokusere på kortsiktige prestasjoner. ', ' Jeg er skeptisk til å investere tid i å forstå nye bransjetrender, da jeg tror de kanskje ikke påvirker mitt arbeid betydelig. ']);
big6.push([4553000, 4550000, '', '', ' Jeg ser på min karriere som en kontinuerlig reise mot personlig vekst, og jeg er villig til å utforske nye muligheter. ', ' Selv om mine langsiktige mål ikke er helt klare, har jeg tro på at jeg vil finne meningsfulle retninger å forfølge. ', ' Jeg føler meg mer komfortabel med å holde meg til min nåværende jobb og rolle i stedet for å ta risikoen ved å prøve noe nytt. ', ' Jeg har liten interesse for å sette langsiktige mål og er fornøyd med å leve i nået uten mye planlegging for fremtiden. ']);
big6.push([4554000, 4550000, '', '', ' Jeg føler meg trygg på mine langsiktige mål, og jeg tar proaktive skritt for å nå dem gjennom hardt arbeid og dedikasjon. ', ' Selv om jeg ikke er helt sikker på min karrierevei, har jeg tro på at jeg vil ta riktige avgjørelser etter hvert som jeg lærer og vokser. ', ' Jeg føler meg usikker på mine langsiktige mål, og jeg unngår ofte å ta initiativ for å nå dem. ', ' Jeg tviler ofte på min evne til å oppnå mine langsiktige mål, og jeg unngår å sette for store forventninger til meg selv. ']);
big6.push([4555000, 4550000, '', '', ' Jeg er drevet av min indre lidenskap og ser på mine langsiktige mål som en kontinuerlig kilde til motivasjon. ', ' Selv om jeg ikke alltid er sikker på mine langsiktige mål, er jeg villig til å utforske og finne veien som passer meg best. ', ' Jeg føler meg ikke så motivert av langsiktige mål, da jeg trives bedre med å ta små steg mot konkrete prestasjoner. ', ' Jeg er skeptisk til viktigheten av langsiktige mål og trives bedre med å ta dagen som den kommer uten store planer for fremtiden. ']);
big6.push([4560000, 4500000, 'Tren&shy;der', 'Bransjekunnskap og trender omfatter en kandidats bevissthet om nåværende utviklinger, fremskritt og markedsdynamikk innenfor deres respektive felt. Å holde seg oppdatert med bransjetrender viser kandidatens dedikasjon til kontinuerlig læring og evne til å tilpasse seg endrede krav. En grundig forståelse av bransjens beste praksis og fremvoksende teknologier posisjonerer enkeltpersoner til å ta informerte beslutninger og være konkurransedyktige innenfor sitt profesjonelle domene.', '', '', '', '']);
big6.push([4561000, 4560000, '', '', ' Jeg holder meg oppdatert på bransjetrender og nye teknologier for å identifisere nye vekstmuligheter. ', ' Selv om jeg kanskje ikke har all den nødvendige bransjekunnskapen ennå, er jeg ivrig etter å lære og holde meg oppdatert. ', ' Jeg er forsiktig med endringer i bransjen og foretrekker å holde meg til kjente metoder og praksis. ', ' Jeg har liten interesse for bransjetrender og føler meg komfortabel med min nåværende kunnskap og metoder. ']);
big6.push([4562000, 4560000, '', '', ' Jeg tror at å forstå bransjetrender er avgjørende for å være konkurransedyktig og relevant i markedet. ', ' Selv om jeg kanskje ikke har all den nødvendige bransjekunnskapen, er jeg villig til å lære og tilpasse meg endringer. ', ' Jeg anser bransjetrender som mindre viktige, da jeg foretrekker å fokusere på mine nåværende arbeidsoppgaver. ', ' Jeg tror at bransjetrender ikke påvirker min nåværende jobb, så jeg har liten interesse for å lære om dem. ']);
big6.push([4563000, 4560000, '', '', ' Jeg søker aktivt muligheter for å utvide min bransjekunnskap og bruke den til å ta informerte beslutninger. ', ' Selv om jeg har begrenset kunnskap om bransjetrender, er jeg åpen for å lære og forbedre min forståelse over tid. ', ' Jeg har liten interesse for å lære om bransjetrender, da jeg føler at min nåværende kompetanse er tilstrekkelig. ', ' Jeg ser på bransjetrender som irrelevant for min nåværende stilling, så jeg har liten motivasjon for å lære om dem. ']);
big6.push([4564000, 4560000, '', '', ' Jeg mener at bransjekunnskap er viktig for å ta strategiske beslutninger som vil ha en positiv innvirkning på organisasjonen. ', ' Selv om jeg ikke er helt oppdatert på bransjetrender, har jeg tillit til at jeg kan tilegne meg den nødvendige kunnskapen. ', ' Jeg anser bransjetrender som mindre relevante, da jeg er mer opptatt av å fokusere på nåværende arbeidsoppgaver. ', ' Jeg har liten interesse for bransjekunnskap, og jeg føler ikke at det vil ha en betydelig innvirkning på min karriere. ']);
big6.push([4565000, 4560000, '', '', ' Jeg tror at kontinuerlig læring om bransjetrender vil gi meg en konkurransefordel og forbedre min karrierevekst. ', ' Selv om jeg ikke er ekspert på bransjetrender, tror jeg at jeg kan forstå dem bedre med tiden og innsats. ', ' Jeg anser bransjetrender som mindre relevante for min nåværende rolle, så jeg har liten motivasjon for å lære om dem. ', ' Jeg føler at min nåværende kunnskap og erfaring er tilstrekkelig, og bransjetrender vil ikke påvirke min nåværende jobb. ']);
