if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([400000, 0, 'Job Candidate'
    , 'Evaluating candidates based on their responses to these statements<br><br>'
            + '<a href="?test=4500000"><b>Norsk kandidattest</b><br>Kandidattest er designet for &aring; indikere ferdighetsvurdering</a><br><br>'
    + 'can provide valuable insights into their mindset, skills, and adaptability. Remember to use these statements as part of a larger evaluation process to make well-rounded hiring decisions.'
, 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er bra for milj&oslash;, samfunn og folk:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er bra for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:'
    , 'Explain in 20 words or less hvorfor dette skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det skjer:'
    , 'Explain in 20 words or less hvorfor dette ikke skjer, og hvorfor det er skadelig for digitalisering, milj&oslash;, samfunn og folk at det ikke skjer:']);

big6.push([410000, 400000,'Technical Skills','Technical skills refer to a candidate\'s proficiency in specific tools, technologies, and methodologies relevant to their field of expertise. These abilities enable individuals to execute tasks effectively, demonstrate expertise, and adapt to changing technological landscapes. Proficiency in programming languages, software applications, data analysis, and other technical competencies are crucial for success in various roles, from software development to engineering and beyond.','','','','']);
big6.push([411000, 410000,'','',' I am excited about exploring new technologies and finding innovative ways to apply them in my work. ',' I have limited experience with the specific tools and technologies required for this job, but I\'m eager to learn. ',' I prefer to stick to the technologies and tools I\'m already familiar with rather than experimenting with unfamiliar ones. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([412000, 410000,'','',' I believe in continuous learning and am always eager to acquire new technical skills to stay ahead in my field. ',' While I lack expertise in certain technical areas, I am confident in my ability to adapt and grow. ',' I feel more comfortable relying on my existing expertise rather than investing time in learning new technical skills. ',' I feel uncomfortable taking on projects that demand technical expertise beyond my current abilities. ']);
big6.push([420000, 400000,'Problem-Solving and Critical Thinking','Problem-solving and critical thinking encompass a candidate\'s ability to analyze complex issues, identify viable solutions, and make informed decisions. These skills involve gathering information, evaluating alternatives, and considering potential consequences to reach optimal conclusions. Candidates who exhibit strong problem-solving and critical thinking skills demonstrate adaptability, creativity, and a capacity to handle challenges effectively in various work scenarios.','','','','']);
big6.push([421000, 420000,'','',' I enjoy taking on complex challenges, as they provide opportunities for creative problem-solving and personal growth. ',' I am not always confident in my problem-solving abilities but enjoy challenging myself to find solutions. ',' When faced with complex problems, I tend to look for established solutions and avoid taking unnecessary risks. ',' I struggle with solving complex problems and often seek others\' help to overcome challenges. ']);
big6.push([422000, 420000,'','',' I believe that trying new approaches, even if they carry some uncertainty, can lead to breakthrough solutions. ',' While I may lack experience in handling complex problems, I\'m willing to invest effort to improve. ',' I am cautious about experimenting with unproven problem-solving methods, as I fear the potential for failure. ',' I tend to avoid tackling complex problems, as I fear making mistakes or reaching ineffective solutions. ']);
big6.push([430000, 400000,'Communication and Interpersonal Skills','Communication and interpersonal skills encompass a candidate\'s capacity to convey ideas clearly, actively listen, and collaborate effectively with team members. Strong communication fosters a positive work environment and promotes successful teamwork, project execution, and client relationships. It involves articulating thoughts, providing constructive feedback, and resolving conflicts while maintaining respect and understanding.','','','','']);
big6.push([431000, 430000,'','',' I value open communication and actively seek out opportunities to collaborate and share ideas with my team. ',' I find it challenging to express my ideas clearly but am open to feedback and opportunities to improve. ',' In group settings, I prefer to listen and observe rather than actively contribute, to avoid saying the wrong thing. ',' I often hesitate to engage in open communication due to my fear of miscommunication or conflict. ']);
big6.push([432000, 430000,'','',' I enjoy participating in group discussions and feel energized by exchanging thoughts and perspectives. ',' Though I lack confidence in group discussions, I am willing to work on my communication skills. ',' I sometimes find it challenging to express my ideas openly in fear of potential misunderstandings. ',' I tend to avoid participating in group discussions, fearing that I may say the wrong things. ']);
big6.push([440000, 400000,'Cultural Fit and Personality Assessment','Cultural fit and personality assessment involve evaluating a candidate\'s alignment with the organization\'s values, mission, and work environment. Assessing cultural fit ensures potential employees will thrive within the company\'s ethos, enhancing team dynamics and overall productivity. Personality traits, such as adaptability, emotional intelligence, and collaboration, are also essential indicators of how candidates will integrate into the company\'s culture.','','','','']);
big6.push([441000, 440000,'','',' I believe that taking calculated risks can lead to significant rewards and foster a culture of innovation. ',' I may not be fully comfortable with risk-taking, but I\'m open to learning and adapting to a dynamic culture. ',' I prefer a stable and predictable work environment where the focus is on maintaining the status quo. ',' I am risk-averse and may struggle to align with a culture that values taking calculated risks. ']);
big6.push([442000, 440000,'','',' I am enthusiastic about working in a dynamic environment that encourages employees to explore new possibilities. ',' While I\'m not the most innovative person, I believe I can contribute positively to a culture that fosters growth. ',' I tend to be cautious when it comes to embracing changes, as they may introduce unforeseen risks. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ']);
big6.push([450000, 400000,'Long-Term Goals and Motivation','Long-term goals and motivation refer to a candidate\'s aspirations and determination to achieve personal and professional objectives. Candidates with clear and ambitious long-term goals demonstrate a commitment to growth and self-improvement, indicating a higher potential for contributing positively to the organization. Motivated individuals possess the drive and resilience to pursue their objectives, leading to higher levels of productivity and engagement.','','','','']);
big6.push([451000, 450000,'','',' I am motivated by the opportunity to make a meaningful impact and create positive change in my career. ',' I have not yet fully defined my long-term career goals but am open to exploring various possibilities. ',' I prefer not to set ambitious long-term goals, as I fear failure or not being able to achieve them. ',' I don\'t pay much attention to industry trends, as I prefer to rely on my existing knowledge and methods. ']);
big6.push([452000, 450000,'','',' Setting ambitious goals excites me, and I am driven to push my boundaries and achieve extraordinary outcomes. ',' While I lack clarity in my long-term goals, I\'m motivated to discover my passion and pursue it. ',' I avoid thinking about long-term goals, as I prefer to focus on short-term accomplishments. ',' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ']);
big6.push([460000, 400000,'Industry Knowledge and Trends','Industry knowledge and trends encompass a candidate\'s awareness of current developments, advancements, and market dynamics within their respective field. Staying up-to-date with industry trends showcases a candidate\'s dedication to continuous learning and adaptability to changing demands. A thorough understanding of industry best practices and emerging technologies positions individuals to make informed decisions and stay competitive in their professional domain','','','','']);
big6.push([461000, 460000,'','',' I keep myself updated on industry trends and emerging technologies to identify new opportunities for growth. ',' I might not be up-to-date with all the recent industry trends, but I\'m eager to stay informed and learn. ',' I am cautious about changes in the industry and prefer to rely on established practices to avoid risks. ',' I have little to no experience with the required technical skills, and I am hesitant to acquire them. ']);
big6.push([462000, 460000, '', '', ' I enjoy exploring potential disruptions in the industry, as they may lead to untapped possibilities. ', ' While I lack in-depth knowledge of current industry trends, I\'m curious to explore and understand them better. ', ' I am hesitant to invest time in understanding new industry trends, as I believe they may not significantly impact my work. ', ' I tend to be skeptical about the long-term impact of emerging trends until they prove their worth. ']);

////////////////////////////////////////////////////////////////////////////////
// Norsk kandidattest
if (big6.length == 0)
    big6.push([0, -1, 'Test', '', '', '', '', '']);

big6.push([4500000, -10, 'Norsk kandidattest', 'Kandidattest er designet for &aring; indikere ferdighetsvurdering'
    , 'Explain in 20 words or less why this discribes you, and how this is a good thing:'
    , 'Explain in 20 words or less why this does not discribe the person tested, and how it is a good thing not to have this trait:'
    , 'Explain in 20 words or less why this discribes you, and how this is not a good thing:'
    , 'Explain in 20 words or less why this does not discribe the person tested, and how it is a bad thing not to have this trait:']);

big6.push([4510000, 4500000, 'Tek&shy;nikk', 'Teknisk ferdighetsvurdering omfatter en kandidats innstilling til kompetanse innen spesifikke verkt&oslash;y, teknologier og metoder som er relevante for deres ekspertiseomr&aring;de. Disse ferdighetene gj&oslash;r individene i stand til &aring; utf&oslash;re oppgaver effektivt, demonstrere ekspertise og tilpasse seg skiftende teknologiske landskap. Beherskelse av programmeringsspr&aring;k, programvareapplikasjoner, dataanalyse og andre tekniske kompetanser er avgj&oslash;rende for suksess i ulike roller, fra programvareutvikling til ingeni&oslash;rfag og videre.', '', '', '', '']);
big6.push([4511000, 4510000, '', '', ' Jeg gleder meg til &aring; utforske nye teknologier og finne innovative m&aring;ter &aring; anvende dem i arbeidet mitt. ', ' Jeg har begrenset erfaring med de spesifikke verkt&oslash;yene og teknologiene som kreves for denne jobben, men jeg er ivrig etter &aring; l&aelig;re. ', ' Jeg foretrekker &aring; holde meg til teknologiene og verkt&oslash;yene jeg allerede er kjent med, heller enn &aring; eksperimentere med ukjente. ', ' Jeg har liten eller ingen erfaring med de n&oslash;dvendige tekniske ferdighetene, og jeg n&oslash;ler med &aring; skaffe dem. ']);
big6.push([4512000, 4510000, '', '', ' Jeg tror p&aring; kontinuerlig l&aelig;ring og er alltid ivrig etter &aring; skaffe nye tekniske ferdigheter for &aring; holde meg oppdatert. ', ' Selv om jeg mangler ekspertise p&aring; visse tekniske omr&aring;der, er jeg trygg p&aring; min evne til &aring; tilpasse meg og vokse. ', ' Jeg f&oslash;ler meg mer komfortabel med &aring; stole p&aring; min eksisterende ekspertise i stedet for &aring; investere tid i &aring; l&aelig;re nye tekniske ferdigheter. ', ' Jeg f&oslash;ler meg ukomfortabel med &aring; ta p&aring; meg prosjekter som krever tekniske ferdigheter utover mine n&aring;v&aelig;rende evner. ']);
big6.push([4513000, 4510001, '', '', ' Mine tekniske ferdigheter er et styrkeomr&aring;de, og jeg er alltid p&aring; utkikk etter muligheter for &aring; bruke dem til &aring; l&oslash;se utfordringer. ', ' Selv om jeg har begrenset erfaring med noen teknologier, er jeg sikker p&aring; at jeg kan l&aelig;re raskt og effektivt. ', ' Jeg fokuserer prim&aelig;rt p&aring; ikke-tekniske aspekter av jobben min og foretrekker &aring; delegere tekniske oppgaver til andre. ', ' Mine tekniske ferdigheter er begrensede, og jeg har liten interesse for &aring; utvide dem. ']);
big6.push([4514000, 4510002, '', '', ' Jeg har erfaring med et bredt spekter av teknologier og f&oslash;ler meg komfortabel med &aring; h&aring;ndtere komplekse tekniske utfordringer. ', ' Mine tekniske ferdigheter er ikke helt oppdaterte, men jeg har en plan for &aring; forbedre dem gjennom kurs og oppl&aelig;ring. ', ' Jeg fokuserer hovedsakelig p&aring; det jeg allerede kan, og jeg er skeptisk til &aring; pr&oslash;ve nye teknologier som kan inneb&aelig;re risiko. ', ' Mine tekniske ferdigheter er utilstrekkelige for &aring; m&oslash;te kravene i denne stillingen, og jeg tviler p&aring; min evne til &aring; utvikle dem tilstrekkelig. ']);
big6.push([4515000, 4510003, '', '', ' Jeg ser p&aring; tekniske utfordringer som spennende muligheter for &aring; l&aelig;re og utvikle meg, og jeg tar initiativ til &aring; forbedre mine ferdigheter. ', ' Jeg har ikke mye erfaring med de spesifikke tekniske verkt&oslash;yene som brukes i denne stillingen, men jeg har tro p&aring; min evne til &aring; mestre dem. ', ' Jeg er tilfreds med min n&aring;v&aelig;rende tekniske kompetanse og f&oslash;ler ingen behov for &aring; utvide den ytterligere. ', ' Mine tekniske ferdigheter er begrensede, og jeg er usikker p&aring; om jeg noensinne vil kunne bli dyktig innen dette omr&aring;det. ']);
big6.push([4520000, 4500000, 'L&oslash;s&shy;ning', 'Probleml&oslash;sning og kritisk tenking omfatter en kandidats evne til &aring; analysere komplekse problemstillinger, identifisere levedyktige l&oslash;sninger og fatte informerte beslutninger. Disse ferdighetene inneb&aelig;rer &aring; samle informasjon, vurdere alternativer og vurdere potensielle konsekvenser for &aring; n&aring; optimale konklusjoner. Kandidater som viser sterke probleml&oslash;snings- og kritisk tenkningsevner, demonstrerer evnen til &aring; tilpasse seg, kreativitet og evne til &aring; h&aring;ndtere utfordringer effektivt i ulike arbeidssituasjoner.', '', '', '', '']);
big6.push([4521000, 4520000, '', '', ' Jeg liker &aring; ta p&aring; meg komplekse utfordringer, da de gir muligheter for kreativ probleml&oslash;sning og personlig vekst. ', ' Jeg er ikke alltid trygg p&aring; mine probleml&oslash;sningsevner, men jeg liker &aring; utfordre meg selv for &aring; finne l&oslash;sninger. ', ' N&aring;r jeg st&aring;r overfor komplekse problemer, har jeg en tendens til &aring; se etter etablerte l&oslash;sninger og unng&aring; un&oslash;dvendige risikoer. ', ' Jeg sliter med &aring; l&oslash;se komplekse problemer og s&oslash;ker ofte hjelp fra andre for &aring; overkomme utfordringer. ']);
big6.push([4522000, 4520000, '', '', ' Jeg tror at &aring; pr&oslash;ve nye tiln&aelig;rminger, selv om de inneb&aelig;rer noe usikkerhet, kan f&oslash;re til gjennombruddsl&oslash;sninger. ', ' Selv om jeg mangler erfaring med &aring; h&aring;ndtere komplekse problemer, er jeg villig til &aring; investere innsats for &aring; forbedre meg. ', ' Jeg er forsiktig med &aring; eksperimentere med upr&oslash;vde probleml&oslash;sningsmetoder, da jeg frykter muligheten for feil. ', ' Jeg unng&aring;r &aring; takle komplekse problemer, da jeg frykter feil eller ineffektive l&oslash;sninger. ']);
big6.push([4523000, 4520000, '', '', ' Jeg trives med utfordringer og ser p&aring; dem som muligheter for &aring; utvikle mine probleml&oslash;sningsevner. ', ' Selv om jeg ikke alltid f&oslash;ler meg trygg i komplekse situasjoner, motiverer det meg til &aring; l&aelig;re og forbedre meg. ', ' Jeg foretrekker &aring; overlate probleml&oslash;sning til andre og fokusere p&aring; mine egne ansvarsomr&aring;der. ', ' Jeg har liten tillit til mine evner til &aring; l&oslash;se komplekse problemer, og jeg unng&aring;r ofte slike situasjoner. ']);
big6.push([4524000, 4520000, '', '', ' Jeg ser p&aring; probleml&oslash;sning som en essensiell del av jobben min, og jeg s&oslash;ker stadig nye m&aring;ter &aring; forbedre arbeidsprosesser p&aring;. ', ' Selv om jeg ikke alltid har l&oslash;sningsalternativer klare, er jeg villig til &aring; konsultere kolleger og samarbeide for &aring; finne de beste l&oslash;sningene. ', ' Jeg f&oslash;lger vanligvis etablerte metoder for probleml&oslash;sning, da jeg foretrekker &aring; unng&aring; risikofylte eksperimenter. ', ' Jeg har vanskelig for &aring; takle komplekse problemer alene, og jeg blir ofte overveldet av slike utfordringer. ']);
big6.push([4525000, 4520000, '', '', ' Jeg f&oslash;ler meg komfortabel med &aring; utforske flere alternativer n&aring;r jeg l&oslash;ser problemer, og jeg er ikke redd for &aring; ta risikoer hvis det er n&oslash;dvendig. ', ' Jeg kan f&oslash;le meg usikker n&aring;r jeg st&aring;r overfor komplekse problemer, men jeg vet at jeg kan l&aelig;re og forbedre mine ferdigheter. ', ' Jeg er motvillig til &aring; forlate kjente l&oslash;sninger, da jeg frykter at ukjente metoder kan f&oslash;re til feil eller forsinkelser. ', ' Jeg har liten tro p&aring; mine probleml&oslash;sningsevner, og jeg foretrekker &aring; s&oslash;ke hjelp fra andre i stedet for &aring; ta p&aring; meg utfordringer selv. ']);
big6.push([4530000, 4500000, 'For&shy;mid&shy;le', 'Kommunikasjon og interpersonlige ferdigheter omfatter en kandidats evne til &aring; formidle ideer klart, lytte aktivt og samarbeide effektivt med teammedlemmer. Sterk kommunikasjon fremmer et positivt arbeidsmilj&oslash; og bidrar til vellykket teamwork, prosjektutf&oslash;relse og kundeforhold. Det inneb&aelig;rer &aring; uttrykke tanker, gi konstruktiv tilbakemelding og l&oslash;se konflikter samtidig som respekt og forst&aring;else opprettholdes.', '', '', '', '']);
big6.push([4531000, 4530000, '', '', ' Jeg verdsetter &aring;pen kommunikasjon og s&oslash;ker aktivt muligheter for samarbeid og deling av ideer med teamet mitt. ', ' Jeg synes det kan v&aelig;re utfordrende &aring; uttrykke ideene mine klart, men jeg er &aring;pen for tilbakemeldinger og muligheter for forbedring. ', ' I gruppesammenhenger foretrekker jeg &aring; lytte og observere i stedet for &aring; aktivt bidra, for &aring; unng&aring; &aring; si noe feil. ', ' Jeg n&oslash;ler ofte med &aring; engasjere meg i &aring;pen kommunikasjon p&aring; grunn av frykt for misforst&aring;elser eller konflikter. ']);
big6.push([4532000, 4530000, '', '', ' Jeg trives med &aring; delta i gruppediskusjoner og f&oslash;ler meg engasjert av &aring; utveksle tanker og perspektiver. ', ' Selv om jeg mangler selvtillit i gruppediskusjoner, er jeg villig til &aring; arbeide med mine kommunikasjonsevner. ', ' Jeg har av og til problemer med &aring; uttrykke ideene mine &aring;pent av frykt for potensielle misforst&aring;elser. ', ' Jeg unng&aring;r &aring; delta i gruppediskusjoner, da jeg frykter at jeg kan si noe feil. ']);
big6.push([4533000, 4530000, '', '', ' Jeg tror at tydelig kommunikasjon er en n&oslash;kkel til vellykket samarbeid, og jeg tar initiativ til &aring; bidra til diskusjoner. ', ' Selv om jeg har noen utfordringer med kommunikasjon, tar jeg aktivt del i teamm&oslash;ter for &aring; forbedre mine ferdigheter. ', ' Jeg er mer komfortabel med &aring; kommunisere skriftlig enn muntlig, og jeg unng&aring;r ofte gruppediskusjoner. ', ' Jeg har lav selvtillit n&aring;r det kommer til kommunikasjon, og jeg f&oslash;ler meg ofte usynlig i gruppesammenhenger. ']);
big6.push([4534000, 4530000, '', '', ' Jeg er trygg p&aring; mine kommunikasjonsevner, og jeg er &aring;pen for &aring; gi og motta konstruktiv tilbakemelding for &aring; forbedre meg. ', ' Selv om jeg noen ganger kan f&oslash;le meg usikker p&aring; mine kommunikasjonsevner, er jeg villig til &aring; ta sjanser for &aring; uttrykke mine ideer. ', ' Jeg unng&aring;r ofte konflikter ved &aring; ikke uttrykke mine meninger eller bekymringer i gruppesammenhenger. ', ' Jeg er redd for &aring; uttrykke mine meninger, da jeg frykter at de vil bli avvist av andre. ']);
big6.push([4535000, 4530000, '', '', ' Jeg tror p&aring; &aring;pen og &aelig;rlig kommunikasjon, og jeg tar initiativ til &aring; skape en inkluderende atmosf&aelig;re i teamet mitt. ', ' Selv om jeg noen ganger kan v&aelig;re reservert i gruppesammenhenger, pr&oslash;ver jeg &aring; utvikle mine kommunikasjonsevner gjennom praksis. ', ' Jeg er tilbakeholden med &aring; uttrykke mine tanker og ideer, da jeg er redd for &aring; bli kritisert av mine kolleger. ', ' Jeg unng&aring;r &aring; ta p&aring; meg oppgaver som krever sterk kommunikasjonsevne, da jeg er usikker p&aring; mine evner p&aring; dette omr&aring;det. ']);
big6.push([4540000, 4500000, 'Kul&shy;tur', 'Kultur og personlighetsvurdering inneb&aelig;rer &aring; vurdere i hvilken grad en kandidat passer inn i organisasjonens verdier, m&aring;l og arbeidsmilj&oslash;. &Aring; vurdere kulturell tilpasning sikrer at potensielle ansatte vil trives i samsvar med bedriftens etos og forbedrer teamdynamikk og produktivitet. Personlighetstrekk som tilpasningsdyktighet, emosjonell intelligens og samarbeidsevner er ogs&aring; viktige indikatorer p&aring; hvordan kandidater vil integrere seg i bedriftens kultur.', '', '', '', '']);
big6.push([4541000, 4540000, '', '', ' Jeg tror at &aring; ta kalkulerte risikoer kan f&oslash;re til betydelige bel&oslash;nninger og fremme en kultur for innovasjon. ', ' Jeg er kanskje ikke helt komfortabel med risikotaking, men jeg er &aring;pen for l&aelig;ring og tilpasning til en dynamisk kultur. ', ' Jeg foretrekker en stabil og forutsigbar arbeidsmilj&oslash; der fokus er p&aring; &aring; opprettholde status quo. ', ' Jeg er risikoavers og kan ha problemer med &aring; tilpasse meg en kultur som verdsetter kalkulerte risikoer. ']);
big6.push([4542000, 4540000, '', '', ' Jeg er entusiastisk med &aring; jobbe i en dynamisk arbeidsmilj&oslash; som oppmuntrer ansatte til &aring; utforske nye muligheter. ', ' Selv om jeg ikke regnes som den mest innovative personen, tror jeg at jeg kan bidra positivt til en kultur for kontinuerlig forbedring. ', ' Jeg er forsiktig med &aring; omfavne endringer i bransjen, da de kan introdusere uforutsette risikoer. ', ' Jeg foretrekker en arbeidsmilj&oslash; der risikotaking er minimal, og jeg er skeptisk til endringer som kan forstyrre stabiliteten. ']);
big6.push([4543000, 4540000, '', '', ' Jeg verdsetter en kultur for samarbeid og gjensidig st&oslash;tte, der ideer blir delt og kolleger st&oslash;tter hverandre. ', ' Selv om jeg noen ganger kan f&oslash;le meg ut av komfortsonen, s&oslash;ker jeg &aring; tilpasse meg og bidra positivt til et teammilj&oslash;. ', ' Jeg er mer komfortabel med &aring; jobbe uavhengig og trives med &aring; l&oslash;se oppgaver p&aring; egen h&aring;nd. ', ' Jeg har vanskelig for &aring; tilpasse meg et samarbeidsorientert arbeidsmilj&oslash;, da jeg trives bedre alene. ']);
big6.push([4544000, 4540000, '', '', ' Jeg ser p&aring; en positiv arbeidskultur som essensiell for trivsel og suksess, og jeg pr&oslash;ver &aring; spre positivitet rundt meg. ', ' Selv om jeg ikke alltid er den mest utadvendte personen, setter jeg pris p&aring; en positiv arbeidskultur og &oslash;nsker &aring; bidra til den. ', ' Jeg kan v&aelig;re reservert og motvillig til &aring; engasjere meg i &aring; bygge en positiv arbeidskultur. ', ' Jeg f&oslash;ler meg ikke som en god kulturell match for arbeidsmilj&oslash;et, og jeg kan ha problemer med &aring; tilpasse meg til bedriftens verdier. ']);
big6.push([4545000, 4540000, '', '', ' Jeg tror p&aring; &aring; bygge et inkluderende arbeidsmilj&oslash; der forskjellige perspektiver blir verdsatt og feiret. ', ' Selv om jeg ikke alltid er den mest sosiale personen, s&oslash;ker jeg &aring; respektere og forst&aring; mine kollegers ulike perspektiver. ', ' Jeg er tilbakeholden med &aring; inkludere andre i beslutningsprosesser, da jeg foretrekker &aring; jobbe selvstendig. ', ' Jeg tror ikke at jeg passer godt inn i arbeidsmilj&oslash;et, og jeg f&oslash;ler meg ofte isolert fra teamet mitt. ']);
big6.push([4550000, 4500000, 'Lang&shy;sik&shy;tig', 'Langsiktige m&aring;l og motivasjon refererer til en kandidats aspirasjoner og vilje til &aring; oppn&aring; personlige og faglige m&aring;l. Kandidater med klare og ambisi&oslash;se langsiktige m&aring;l demonstrerer forpliktelse til vekst og selvforbedring, noe som indikerer h&oslash;y potensial for &aring; bidra positivt til organisasjonen. Motiverte individer besitter drivkraft og utholdenhet for &aring; forf&oslash;lge m&aring;lene sine, noe som f&oslash;rer til h&oslash;yere produktivitet og engasjement.', '', '', '', '']);
big6.push([4551000, 4550000, '', '', ' Jeg blir motivert av muligheten til &aring; gj&oslash;re en meningsfylt innvirkning og skape positiv endring i karrieren min. ', ' Jeg har enn&aring; ikke fullstendig definert mine langsiktige karrierem&aring;l, men jeg er &aring;pen for &aring; utforske ulike muligheter. ', ' Jeg foretrekker &aring; ikke sette ambisi&oslash;se langsiktige m&aring;l, da jeg frykter at jeg kan mislykkes eller ikke kunne oppn&aring; dem. ', ' Jeg bryr meg ikke mye om bransjetrender, da jeg foretrekker &aring; stole p&aring; min eksisterende kunnskap og metoder. ']);
big6.push([4552000, 4550000, '', '', ' &Aring; sette ambisi&oslash;se m&aring;l inspirerer meg, og jeg er drevet til &aring; utfordre mine grenser og oppn&aring; ekstraordin&aelig;re resultater. ', ' Selv om jeg mangler klarhet i mine langsiktige m&aring;l, er jeg motivert for &aring; oppdage min lidenskap og forf&oslash;lge den. ', ' Jeg unng&aring;r &aring; tenke p&aring; langsiktige m&aring;l, da jeg foretrekker &aring; fokusere p&aring; kortsiktige prestasjoner. ', ' Jeg er skeptisk til &aring; investere tid i &aring; forst&aring; nye bransjetrender, da jeg tror de kanskje ikke p&aring;virker mitt arbeid betydelig. ']);
big6.push([4553000, 4550000, '', '', ' Jeg ser p&aring; min karriere som en kontinuerlig reise mot personlig vekst, og jeg er villig til &aring; utforske nye muligheter. ', ' Selv om mine langsiktige m&aring;l ikke er helt klare, har jeg tro p&aring; at jeg vil finne meningsfulle retninger &aring; forf&oslash;lge. ', ' Jeg f&oslash;ler meg mer komfortabel med &aring; holde meg til min n&aring;v&aelig;rende jobb og rolle i stedet for &aring; ta risikoen ved &aring; pr&oslash;ve noe nytt. ', ' Jeg har liten interesse for &aring; sette langsiktige m&aring;l og er forn&oslash;yd med &aring; leve i n&aring;et uten mye planlegging for fremtiden. ']);
big6.push([4554000, 4550000, '', '', ' Jeg f&oslash;ler meg trygg p&aring; mine langsiktige m&aring;l, og jeg tar proaktive skritt for &aring; n&aring; dem gjennom hardt arbeid og dedikasjon. ', ' Selv om jeg ikke er helt sikker p&aring; min karrierevei, har jeg tro p&aring; at jeg vil ta riktige avgj&oslash;relser etter hvert som jeg l&aelig;rer og vokser. ', ' Jeg f&oslash;ler meg usikker p&aring; mine langsiktige m&aring;l, og jeg unng&aring;r ofte &aring; ta initiativ for &aring; n&aring; dem. ', ' Jeg tviler ofte p&aring; min evne til &aring; oppn&aring; mine langsiktige m&aring;l, og jeg unng&aring;r &aring; sette for store forventninger til meg selv. ']);
big6.push([4555000, 4550000, '', '', ' Jeg er drevet av min indre lidenskap og ser p&aring; mine langsiktige m&aring;l som en kontinuerlig kilde til motivasjon. ', ' Selv om jeg ikke alltid er sikker p&aring; mine langsiktige m&aring;l, er jeg villig til &aring; utforske og finne veien som passer meg best. ', ' Jeg f&oslash;ler meg ikke s&aring; motivert av langsiktige m&aring;l, da jeg trives bedre med &aring; ta sm&aring; steg mot konkrete prestasjoner. ', ' Jeg er skeptisk til viktigheten av langsiktige m&aring;l og trives bedre med &aring; ta dagen som den kommer uten store planer for fremtiden. ']);
big6.push([4560000, 4500000, 'Tren&shy;der', 'Bransjekunnskap og trender omfatter en kandidats bevissthet om n&aring;v&aelig;rende utviklinger, fremskritt og markedsdynamikk innenfor deres respektive felt. &Aring; holde seg oppdatert med bransjetrender viser kandidatens dedikasjon til kontinuerlig l&aelig;ring og evne til &aring; tilpasse seg endrede krav. En grundig forst&aring;else av bransjens beste praksis og fremvoksende teknologier posisjonerer enkeltpersoner til &aring; ta informerte beslutninger og v&aelig;re konkurransedyktige innenfor sitt profesjonelle domene.', '', '', '', '']);
big6.push([4561000, 4560000, '', '', ' Jeg holder meg oppdatert p&aring; bransjetrender og nye teknologier for &aring; identifisere nye vekstmuligheter. ', ' Selv om jeg kanskje ikke har all den n&oslash;dvendige bransjekunnskapen enn&aring;, er jeg ivrig etter &aring; l&aelig;re og holde meg oppdatert. ', ' Jeg er forsiktig med endringer i bransjen og foretrekker &aring; holde meg til kjente metoder og praksis. ', ' Jeg har liten interesse for bransjetrender og f&oslash;ler meg komfortabel med min n&aring;v&aelig;rende kunnskap og metoder. ']);
big6.push([4562000, 4560000, '', '', ' Jeg tror at &aring; forst&aring; bransjetrender er avgj&oslash;rende for &aring; v&aelig;re konkurransedyktig og relevant i markedet. ', ' Selv om jeg kanskje ikke har all den n&oslash;dvendige bransjekunnskapen, er jeg villig til &aring; l&aelig;re og tilpasse meg endringer. ', ' Jeg anser bransjetrender som mindre viktige, da jeg foretrekker &aring; fokusere p&aring; mine n&aring;v&aelig;rende arbeidsoppgaver. ', ' Jeg tror at bransjetrender ikke p&aring;virker min n&aring;v&aelig;rende jobb, s&aring; jeg har liten interesse for &aring; l&aelig;re om dem. ']);
big6.push([4563000, 4560000, '', '', ' Jeg s&oslash;ker aktivt muligheter for &aring; utvide min bransjekunnskap og bruke den til &aring; ta informerte beslutninger. ', ' Selv om jeg har begrenset kunnskap om bransjetrender, er jeg &aring;pen for &aring; l&aelig;re og forbedre min forst&aring;else over tid. ', ' Jeg har liten interesse for &aring; l&aelig;re om bransjetrender, da jeg f&oslash;ler at min n&aring;v&aelig;rende kompetanse er tilstrekkelig. ', ' Jeg ser p&aring; bransjetrender som irrelevant for min n&aring;v&aelig;rende stilling, s&aring; jeg har liten motivasjon for &aring; l&aelig;re om dem. ']);
big6.push([4564000, 4560000, '', '', ' Jeg mener at bransjekunnskap er viktig for &aring; ta strategiske beslutninger som vil ha en positiv innvirkning p&aring; organisasjonen. ', ' Selv om jeg ikke er helt oppdatert p&aring; bransjetrender, har jeg tillit til at jeg kan tilegne meg den n&oslash;dvendige kunnskapen. ', ' Jeg anser bransjetrender som mindre relevante, da jeg er mer opptatt av &aring; fokusere p&aring; n&aring;v&aelig;rende arbeidsoppgaver. ', ' Jeg har liten interesse for bransjekunnskap, og jeg f&oslash;ler ikke at det vil ha en betydelig innvirkning p&aring; min karriere. ']);
big6.push([4565000, 4560000, '', '', ' Jeg tror at kontinuerlig l&aelig;ring om bransjetrender vil gi meg en konkurransefordel og forbedre min karrierevekst. ', ' Selv om jeg ikke er ekspert p&aring; bransjetrender, tror jeg at jeg kan forst&aring; dem bedre med tiden og innsats. ', ' Jeg anser bransjetrender som mindre relevante for min n&aring;v&aelig;rende rolle, s&aring; jeg har liten motivasjon for &aring; l&aelig;re om dem. ', ' Jeg f&oslash;ler at min n&aring;v&aelig;rende kunnskap og erfaring er tilstrekkelig, og bransjetrender vil ikke p&aring;virke min n&aring;v&aelig;rende jobb. ']);
